In [1]:
import pandas as pd

# 读取 JSON 文件
df_meta = pd.read_json("dataset/googlelocal/light_meta_LLM.json", lines=True)
df_review = pd.read_json("dataset/googlelocal/light_review_LLM.json", lines=True)

In [2]:
df_meta

,name,gmap_id,description,num_of_reviews,price,hours,MISC,state,relative_results,url
0,City Textile,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,"This textile exporter located in Los Angeles,...",6,NaN,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
1,San Soo Dang,0x80c2c778e3b73d33:0xbdc58662a4a97d49,This vibrant Korean restaurant in Los Angeles...,18,NaN,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,Nova Fabrics,0x80c2c89923b27a41:0x32041559418d447,"This fabric store in Los Angeles, CA 90021 of...",6,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nobel Textile Co,0x80c2c632f933b073:0xc31785961fe826a6,"This fabric store in Los Angeles, CA 90021 of...",7,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Matrix International Textiles,0x80c2cf163db6bc89:0x219484e2edbcfa41,"This Fabric store in Commerce, CA 90023 offer...",6,NaN,"[[Thursday, 8:30AM–5:30PM], [Friday, 8:30AM–5:...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5:30PM,"[0x80c2cf042a5d9561:0xd0024ad6f81f1335, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...
74,Taitz Orly DDS,0x80dcebb0f57d2047:0x9e642a2ee5eed29c,"This Dentist in Rancho Santa Margarita, CA 92...",48,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM,"[0x80dcebb0f4c49b8f:0xf38d68e0039fde6a, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...
75,St John Knits International Inc,0x80dcde96809ca927:0x9ba5b9ae5526f1fc,"This Women's clothing store in Irvine, CA 926...",8,NaN,"[[Thursday, 10AM–6PM], [Friday, 10AM–6PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 10AM,"[0x80dcdcf56eb54575:0x233b36a32226f099, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...
76,NEX Barbershop,0x80d9532636343fc5:0x8ab94fe13542f7b,"This Barber shop in Coronado, CA 92118 offers...",8,NaN,"[[Thursday, 7AM–5PM], [Friday, 7AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5PM,"[0x80d9534c8adf3713:0x4ac67169e4a52318, 0x80d9...",https://www.google.com/maps/place//data=!4m2!3...
77,Widows Peak Salon,0x80c2c6594138441d:0x59088f7293270c3f,"This modern hair salon in Los Angeles, CA 900...",35,NaN,"[[Thursday, 11AM–8PM], [Friday, 11AM–7PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 11AM,"[0x80c2c65afdaac50b:0x1a6b3ee710d6be7c, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
78,The Dream Junction,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c,"Located in Santa Ana, CA 92704, this digital ...",48,NaN,"[[Thursday, 9AM–7PM], [Friday, 9AM–7PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM,"[0x80dcde8dfce91103:0x32cecf2be8ce14b3, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...

In [3]:
df_review

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.131656e+20,Michael Rizal,"September 03, 2020 at 04:15 PM",5,"Located in the vibrant area of Los Angeles, CA...",None,None,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
1,1.012264e+20,Faranak Rafizadeh,2021-04-12 17:07:52,5,Los Angeles is known for its vibrant culture a...,None,None,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
2,1.111677e+20,Javier Perez,2018-04-23 16:24:26,5,I had a fantastic experience at this amazing s...,None,None,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
3,1.162309e+20,Luis P.,2017-07-10 22:12:19,5,I had an amazing experience at this charming c...,None,None,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
4,1.041817e+20,His Mama Cakez,"May 19, 2021 at 03:55 AM",3,I had an amazing experience at this charming c...,None,None,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
...,...,...,...,...,...,...,...,...
1995,1.015530e+20,Bohemian Harlem,"20 Dec 2019, 21:57",1,Santa Ana is known for its vibrant atmosphere ...,None,None,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1996,1.053268e+20,Agent Skg,"August 25, 2020 at 12:34 AM",1,"Santa Ana has many options for service, but un...",None,None,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1997,1.075275e+20,Riding Updrafts,"October 22, 2019 at 01:23 PM",1,"Located in the vibrant city of Santa Ana, Prin...",None,None,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1998,1.090889e+20,money maker,"23 Oct 2019, 14:06",1,"Located in Santa Ana, CA 92704, I was eager to...",None,None,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1999,1.095447e+20,Work Zone Fitness,"January 26, 2018 at 10:25 AM",3,"Santa Ana is known for its vibrant art scene, ...",None,None,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c

In [19]:
print(df_review.dtypes)
print(df_meta.dtypes)

user_id    float64
name        object
time        object
rating       int64
text        object
pics        object
resp        object
gmap_id     object
dtype: object
name                 object
gmap_id              object
description          object
num_of_reviews        int64
price               float64
hours                object
MISC                 object
state                object
relative_results     object
url                  object
dtype: object

In [4]:
import pandas as pd

# 读取 JSON 文件
df_meta = pd.read_json("dataset/googlelocal/light_meta_LLM.json", lines=True)

# 删除指定列
df_meta_v1 = df_meta.drop(columns=["price", "relative_results", "url"], errors='ignore')

# 保存为 JSON 文件（可选择覆盖原文件或另存为新文件）
df_meta_v1.to_json("dataset/googlelocal/light_meta_LLM_tt.json", orient="records", lines=True)

df_meta_v1

,name,gmap_id,description,num_of_reviews,hours,MISC,state
0,City Textile,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,"This textile exporter located in Los Angeles,...",6,None,None,Open now
1,San Soo Dang,0x80c2c778e3b73d33:0xbdc58662a4a97d49,This vibrant Korean restaurant in Los Angeles...,18,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM
2,Nova Fabrics,0x80c2c89923b27a41:0x32041559418d447,"This fabric store in Los Angeles, CA 90021 of...",6,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM
3,Nobel Textile Co,0x80c2c632f933b073:0xc31785961fe826a6,"This fabric store in Los Angeles, CA 90021 of...",7,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM
4,Matrix International Textiles,0x80c2cf163db6bc89:0x219484e2edbcfa41,"This Fabric store in Commerce, CA 90023 offer...",6,"[[Thursday, 8:30AM–5:30PM], [Friday, 8:30AM–5:...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5:30PM
...,...,...,...,...,...,...,...
74,Taitz Orly DDS,0x80dcebb0f57d2047:0x9e642a2ee5eed29c,"This Dentist in Rancho Santa Margarita, CA 92...",48,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM
75,St John Knits International Inc,0x80dcde96809ca927:0x9ba5b9ae5526f1fc,"This Women's clothing store in Irvine, CA 926...",8,"[[Thursday, 10AM–6PM], [Friday, 10AM–6PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 10AM
76,NEX Barbershop,0x80d9532636343fc5:0x8ab94fe13542f7b,"This Barber shop in Coronado, CA 92118 offers...",8,"[[Thursday, 7AM–5PM], [Friday, 7AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5PM
77,Widows Peak Salon,0x80c2c6594138441d:0x59088f7293270c3f,"This modern hair salon in Los Angeles, CA 900...",35,"[[Thursday, 11AM–8PM], [Friday, 11AM–7PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 11AM
78,The Dream Junction,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c,"Located in Santa Ana, CA 92704, this digital ...",48,"[[Thursday, 9AM–7PM], [Friday, 9AM–7PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM

In [6]:
import pandas as pd

# 读取 JSON 文件
df_review = pd.read_json("dataset/googlelocal/light_review_LLM.json", lines=True)

# 删除指定列
df_review_v1 = df_review.drop(columns=["pics", "user_id", "resp"], errors='ignore')

# 保存为 JSON 文件（可选择覆盖原文件或另存为新文件）
df_review_v1.to_json("dataset/googlelocal/light_review_LLM_tt.json", orient="records", lines=True)

df_review_v1

,name,time,rating,text,gmap_id
0,Michael Rizal,"September 03, 2020 at 04:15 PM",5,"Located in the vibrant area of Los Angeles, CA...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
1,Faranak Rafizadeh,2021-04-12 17:07:52,5,Los Angeles is known for its vibrant culture a...,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
2,Javier Perez,2018-04-23 16:24:26,5,I had a fantastic experience at this amazing s...,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
3,Luis P.,2017-07-10 22:12:19,5,I had an amazing experience at this charming c...,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
4,His Mama Cakez,"May 19, 2021 at 03:55 AM",3,I had an amazing experience at this charming c...,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9
...,...,...,...,...,...
1995,Bohemian Harlem,"20 Dec 2019, 21:57",1,Santa Ana is known for its vibrant atmosphere ...,0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1996,Agent Skg,"August 25, 2020 at 12:34 AM",1,"Santa Ana has many options for service, but un...",0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1997,Riding Updrafts,"October 22, 2019 at 01:23 PM",1,"Located in the vibrant city of Santa Ana, Prin...",0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1998,money maker,"23 Oct 2019, 14:06",1,"Located in Santa Ana, CA 92704, I was eager to...",0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c
1999,Work Zone Fitness,"January 26, 2018 at 10:25 AM",3,"Santa Ana is known for its vibrant art scene, ...",0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c

In [8]:
import json
from pathlib import Path

def load_json_lines(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return [json.loads(line.strip()) for line in f if line.strip()]
    except Exception as e:
        print(f"❌ Error loading {file_path}: {e}")
        return []

def save_json_lines(data, output_path):
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            for record in data:
                f.write(json.dumps(record) + "\n")
        print(f"✅ Saved {len(data)} records to {output_path}")
    except Exception as e:
        print(f"❌ Error saving {output_path}: {e}")

def relabel_gmap_ids(meta_data, review_data):
    # Step 1: Create consistent mapping from original gmap_id → new_id (e.g., gmap_0)
    id_map = {}
    for i, entry in enumerate(meta_data):
        original_id = entry.get("gmap_id")
        new_id = f"gmap_{i}"
        id_map[original_id] = new_id
        entry["gmap_id"] = new_id  # Replace in meta_data

    # Step 2: Replace in review_data
    replaced = 0
    for r in review_data:
        original = r.get("gmap_id")
        if original in id_map:
            r["gmap_id"] = id_map[original]
            replaced += 1

    print(f"✅ Replaced {len(id_map)} unique gmap_ids in meta_data")
    print(f"✅ Replaced {replaced} gmap_ids in review_data")
    return meta_data, review_data

if __name__ == "__main__":
    # === File paths ===
    meta_path = "dataset/googlelocal/light_meta_LLM_tt.json"
    review_path = "dataset/googlelocal/light_review_LLM_tt.json"
    new_meta_path = "dataset/googlelocal/light_meta_LLM_tt.json"
    new_review_path = "dataset/googlelocal/light_review_LLM_tt.json"

    # === Load original data ===
    meta_data = load_json_lines(meta_path)
    review_data = load_json_lines(review_path)

    # === Replace gmap_id ===
    meta_new, review_new = relabel_gmap_ids(meta_data, review_data)

    # === Save to new files ===
    save_json_lines(meta_new, new_meta_path)
    save_json_lines(review_new, new_review_path)

✅ Replaced 79 unique gmap_ids in meta_data
✅ Replaced 2000 gmap_ids in review_data
✅ Saved 79 records to dataset/googlelocal/light_meta_LLM_tt.json
✅ Saved 2000 records to dataset/googlelocal/light_review_LLM_tt.json

In [9]:
print(df_review_v1.dtypes)
print(df_meta_v1.dtypes)

name       object
time       object
rating      int64
text       object
gmap_id    object
dtype: object
name              object
gmap_id           object
description       object
num_of_reviews     int64
hours             object
MISC              object
state             object
dtype: object