In [1]:
from sqlalchemy import create_engine
import pandas as pd

# 数据库连接信息
user = "root"
password = "20041025"  # 替换为你的密码
host = "localhost"
port = "3306"
database = "ucb_db"

# 创建 SQLAlchemy 引擎
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

# 假设你想读取一个叫 books 的表
df_books = pd.read_sql("SELECT * FROM books_info;", engine)
df_books.head()

,title,subtitle,author,rating_number,features,description,price,store,categories,details,book_id
0,Chaucer,"Hardcover – Import, January 1, 2004","{""avatar"": ""https://m.media-amazon.com/images/...",29,[],[],8.23,Peter Ackroyd (Author),"[""Books"", ""Literature & Fiction"", ""History & C...","Published by Chatto & Windus, the first editio...",bookid_1
1,Notes from a Kidwatcher,First Edition,"{""avatar"": ""https://m.media-amazon.com/images/...",1,"[""Contains 23 selected articles by this influe...","[""About the Author"", ""SANDRA WILDE, Ph.D., is ...",3.52,Sandra Wilde (Editor),"[""Books"", ""Reference"", ""Words, Language & Gram...","This book, published by Heinemann in its first...",bookid_2
2,Service: A Navy SEAL at War,"Hardcover – May 8, 2012","{""avatar"": ""https://m.media-amazon.com/images/...",3421,"[""Marcus Luttrell, author of the #1 bestseller...","[""Review"", ""Praise for SERVICE\""An action-pack...",17.17,"Marcus Luttrell (Author), James D. Hornfischer","[""Books"", ""Biographies & Memoirs"", ""Leaders & ...","This book, published by Little, Brown and Comp...",bookid_3
3,Monstrous Stories #4: The Day the Mice Stood S...,"Paperback – October 29, 2013",None,40,"[""Funny, light-hearted monster stories that ar...",[],7.43,Dr. Roach (Author),"[""Books"", ""Children's Books"", ""Science Fiction...","This book, published by Scholastic Paperbacks ...",bookid_4
4,Parker & Knight,Kindle Edition,"{""avatar"": ""https://m.media-amazon.com/images/...",381,"[""From REMINGTON KANE, the author of The Taken...",[],0.00,Remington Kane (Author) Format: Kindle Edition,"[""Books"", ""Mystery, Thriller & Suspense"", ""Thr...","The book was published on May 18, 2014, and is...",bookid_5

In [20]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine
from openai import AzureOpenAI
# MySQL配置
mysql_password = "20041025"  # 替换为你的MySQL密码
mysql_db = "ucb_db"
mysql_table = "books_info"

# ========== Configuration ========== #
client = AzureOpenAI(
    api_key="609ced4d971240b8a08f7fb0e6d846ea",
    api_version="2024-08-01-preview",
    azure_endpoint="https://promptdelta-nc.openai.azure.com",  # 不要加 /v1
)
deployment_name = "gpt-4o-mini" 

def fetch_business_data():
    try:
        conn = mysql.connector.connect(
            host="localhost",
            user="root",
            password=mysql_password,
            database=mysql_db
        )
        cursor = conn.cursor()
        cursor.execute(f"SELECT * FROM {mysql_table}")
        column_names = [desc[0] for desc in cursor.description]
        rows = cursor.fetchall()
        conn.close()
        return rows, column_names
    except Exception as e:
        print(f"❌ MySQL connection failed: {e}")
        return [], []

rows, column_names = fetch_business_data()
books = [dict(zip(column_names, row)) for row in rows]
print(f"✅ Total {len(books)} books")


def get_decade_by_llm(details, client, deployment_name):
    prompt = (
        "Given the following book details, extract the decade in which the book was first published.\n"
        "Respond with a single answer in the format like '1980s', '2000s', etc. If uncertain because no year information is included in the book details, just answer Uncertain.\n\n"
        f"Details: {details}"
    )
    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a helpful assistant that extracts publishing decades from book descriptions."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=10
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"❌ GPT error: {e}")
        return "Unknown"

for i, book in enumerate(books):
    details = book.get("details", "")
    if not details or details.strip() == "":
        book["decade"] = "Unknown"
        print(f"❌ [{i}] Unknown")
        continue
    decade = get_decade_by_llm(details, client, deployment_name)
    book["decade"] = decade
    print(f"✅ [{i}] {book.get('title', 'Untitled')} → {decade}")
book_id_to_decade = {b["book_id"]: b["decade"] for b in books}
# 构造 DataFrame（方便后续分析）
df_books = pd.DataFrame(books)
print(df_books["decade"].value_counts())  # 看每个 decade 的分布

✅ Total 200 books
✅ [0] Chaucer → 2000s
✅ [1] Notes from a Kidwatcher → 1990s
✅ [2] Service: A Navy SEAL at War → 2010s
✅ [3] Monstrous Stories #4: The Day the Mice Stood Still → Uncertain
✅ [4] Parker & Knight → 2010s
✅ [5] Writings from a Black Woman Living in the Land of the "Free": Strength, Power, Resilience → 2020s
✅ [6] Child Development: A Practitioner's Guide:2nd (Second) edition → 1990s
✅ [7] Make: Electronics: Learning Through Discovery → 2010s
✅ [8] Reunion: The Children of Lauderdale Park → 2010s
✅ [9] Four Centuries of American Education → 2000s
✅ [10] Mining Engineers and the American West: The Lace-Boot Brigarde, 1849-1933 → 1990s
✅ [11] Heart of Silk and Shadows: A Fae Fantasy Romance (Fae Isles) → 2020s
✅ [12] Girl Made of Glass → 2020s
✅ [13] The Old Man and the Pirate Princess → 2010s
✅ [14] Japanese Girls and Women → 2000s
✅ [15] Behavior Principles in Everyday Life → 1990s
✅ [16] PQL 3 - Lola (Spanish Edition) → 1980s
✅ [17] A sermon, preached at the execution of Moses Paul, an Indian: who was executed at New-Haven, on the 2d of September, 1772, for the murder of Mr. Moses ... 1771 : preached at the desire of said Paul. → 2010s
✅ [18] Business Associations: Agency, Partnerships, LLCs, and Corporations- 2013 Statutes and Rules → Uncertain
✅ [19] Inspector Imanishi Investigates (Soho Crime) → 2000s
✅ [20] Officially Dead → 1940s
✅ [21] Dine In! → 2000s
✅ [22] The Promise of Love (The Book of Love) → 2020s
✅ [23] Statesmen of the Lost Cause → 1930s
✅ [24] A Monster Sandwich (The Story Box - Level 1 - Set B - for Emergent Readers) [Paperback] → Uncertain
✅ [25] Sounds from the Heart: Learning to Listen to Girls → 1990s
✅ [26] Hunting Evil → Uncertain
✅ [27] Les Chiens De Paris → 1990s
✅ [28] Acoustic & Digital Piano Buyer Fall 2017: Supplement to The Piano Book → 2010s
✅ [29] Sugary Sweets (A Taste of Love Series) → 2010s
✅ [30] The English Monster: or, The Melancholy Transactions of William Ablass → 2010s
✅ [31] The Very Hungry Caterpillar (English and Arabic Edition) → 1990s
✅ [32] More Together: 25 Years of Peer Practice at On Our Own Charlottesville → 2010s
✅ [33] Never Sniff a Gift Fish → 1980s
✅ [34] Markov Chain Monte Carlo: Stochastic Simulation for Bayesian Inference, Second Edition (Chapman & Hall/CRC Texts in Statistical Science) → 2000s
✅ [35] Therapy Mammals → 2010s
✅ [36] A Most Dangerous Book: Tacitus's Germania from the Roman Empire to the Third Reich → 2010s
✅ [37] The Prophet: With Original 1923 Illustrations by the Author → 2010s
✅ [38] The Melancholy Strumpet Master → 2020s
✅ [39] Egypt (Enchantment of the World) → 2010s
✅ [40] Shane, Sheba and Sky: From Abandoned to Loved, How Three Rescue Dogs Transformed One Man's Life → 2010s
✅ [41] Law and Legitimacy in the Supreme Court → 2010s
✅ [42] Retreat Yourself: How To Create Your Own Writer's Retreat → 2010s
✅ [43] Reptilian → 2010s
✅ [44] Grade Five Music Theory: for ABRSM Candidates (MyMusicTheory Complete Courses) → 2010s
✅ [45] Oregon Birds: A Folding Pocket Guide to Familiar Species (Wildlife and Nature Identification) → 2010s
✅ [46] Who'd a thought it! → 1980s
✅ [47] Clark the Shark: Tooth Trouble, No. 1 → 2010s
✅ [48] Primeval: A Journal of the Uncanny - Issue #1 → 2010s
✅ [49] The Mercenary Code (The Shattering of Kingdoms) → 2010s
✅ [50] Health Information Networking Course Booklet → 2010s
✅ [51] I Hadn't Meant to Tell You This → 1990s
✅ [52] Graphite Rod Repair → 1990s
✅ [53] Favorite Thorton W. Burgess Stories: 6 Books → 2000s
✅ [54] Behind the Wheel (Choose Your Own Adventure #35)(Paperback/Revised) → 2010s
✅ [55] MCSE/MCTS SQL Server 2008 R2 / 2012 Exam 70- 432 & 462 ExamFOCUS Study Notes & Review Questions → 2010s
✅ [56] Goodnight Riley and the Moon, It's Almost Bedtime: Personalized Children’s Books, Personalized Gifts, and Bedtime Stories (A Magnificent Me! estorytime.com Series) → 2010s
✅ [57] 50 Ways to Wear Denim → 2010s
✅ [58] Comprehension Mini-lessons → 2000s
✅ [59] Tom Selleck: An Unauthorized Biography → 1980s
✅ [60] Collectible Beer Trays (A Schiffer Book for Collectors) → 1990s
✅ [61] David Busch's Canon EOS Rebel T6/1300D Guide to Digital SLR Photography (The David Busch Camera Guide Series) → 2010s
✅ [62] How to Open & Operate a Financially Successful Web-Based Business: With Companion CD-ROM → 2000s
✅ [63] Beyond Success: Building a Personal, Financial, and Philanthropic Legacy → 2000s
✅ [64] Beatles in Their Own Words → 1970s
✅ [65] The Soaring Pilot's Manual → 2000s
✅ [66] Novi V-8 Indy Cars 1941-1965 → 2000s
✅ [67] Redhook: A Microbrew Success Story → 1990s
✅ [68] Out of Sheer Rage: Wrestling with D. H. Lawrence → 2000s
✅ [69] Polly and the Shadow Goblin: Book 2, Mother of Witches → 2010s
✅ [70] The Knowledge-Value Revolution or a History of the Future → 1990s
✅ [71] Sunrise Highway (Lourdes Robles Novels Book 2) → 2010s
✅ [72] Steck-Vaughn GED: Test Prep 2014 GED Social Studies Spanish Student Workbook (Spanish Edition) → 2010s
✅ [73] Child Of The King A Journey of Hope Book 1: Earthly Story With A Heavenly Message → 2020s
✅ [74] A Trip Around the World: A Pieced & Applique Quilt featuring easy machine-sewing techniques → 1980s
✅ [75] Coffee Cup Cozies (Christmas Crochet Book 1) → 2010s
✅ [76] One September Morning → 2000s
✅ [77] Classic Football Art: Originally Published in 19th Century Newspapers: Hundreds of Illustrations from the Dawn of the Great American Game (The Lost Century of Sports Collection) → 2010s
✅ [78] You Will Never Be Him → 2010s
✅ [79] Mongoose, R.I.P. → 1980s
✅ [80] Need You Now - A Story of Hope → 2010s
✅ [81] Fire Cracker → 1990s
✅ [82] Bisous and Brioche: Classic French Recipes and Family Favorites from a Life in France → 2020s
✅ [83] Local Honey → 2010s
✅ [84] NICET Fire Alarm Systems Level 1 Study Guide → 2010s
✅ [85] Appropriate: The Houses Of Joseph Esherick (Environmental Design Archives at the University of California, Berkeley Series) (Environmental Design Archives ... University of California, Berkeley Series → 2000s
✅ [86] Elegance: A Guide to Quality in Menswear → 1980s
✅ [87] Ed Delahanty in the Emerald Age of Baseball → 2000s
✅ [88] I'll Ride For My Hood: A Salty Love Story → 2010s
❌ [89] Unknown
✅ [90] The Liquor King of the Blue Ridge and Other Stories of Aho → 2010s
✅ [91] Outage → 2010s
✅ [92] Simantov → 2020s
✅ [93] Modern Fishing Lure Collectibles, Vol. 3: Identification & Value Guide → 2000s
✅ [94] The Strong-Willed Child: Birth Through Adolescence → 1980s
✅ [95] Cheer Up, Ben Franklin! (Young Historians) → 2010s
✅ [96] Route 66 Dream Castle: Claude Calmes and Clinton's Hotel Calmez → Uncertain
✅ [97] Hollywood Confessions: Hollywood Headlines Book #3 (Hollywood Headlines Mysteries) → 2010s
✅ [98] Buddy the Soldier Bear → 2010s
✅ [99] How To Draw Manga Supersize Volume 2 (How to Draw Manga (Antarctic Press)) → 2000s
✅ [100] Knowing When To Die: Uncollected Stories → 2010s
✅ [101] Lunch at 10 Pomegranate Street: A Collection of Recipes to Share → Uncertain
❌ [102] Unknown
✅ [103] Vienna 1900: Klimt, Schiele, and Their Times: A Total Work of Art → 2010s
✅ [104] Greek mythology → 1980s
✅ [105] Looking for Peyton Place: A Novel → 2000s
✅ [106] The Grim Hunt: Crown of Madness → 2020s
✅ [107] The Library Book → 2020s
✅ [108] All the Way to the Gallows → 1990s
❌ [109] Unknown
✅ [110] Can You Buy Me The Wind? → 2010s
❌ [111] Unknown
✅ [112] Killing His Fear → 2010s
✅ [113] A Shepherd's Watch : Through the Seasons With One Man and His Dogs → 2000s
✅ [114] The Mid-Atlantic Championship → 2010s
✅ [115] From the Earth to the Moon by Jules Verne, Fiction, Fantasy & Magic → 2000s
✅ [116] Land Surveying Law: With Study Guide Questions → 2000s
✅ [117] Introduction to Dental Local Anaesthesia → 1990s
✅ [118] The Mystery of the Multiple Mothers: A Cub County Caper → 2010s
✅ [119] Caroline's Color Dreams: Los Sueños Coloridos De Carolina : Babl Children's Books in Spanish and English → 2010s
✅ [120] Bambini: The Italian Approach to Infant/Toddler Care (Early Childhood Education Series) → 2000s
✅ [121] Childe Harold of Dysna → 2020s
✅ [122] Comprehensive Commercial Law: 2010 Statutory Supplement → 2010s
✅ [123] Skeleton Play: A Fun, Rhyming Halloween Book for Kids! (1) → 2010s
✅ [124] The CEO of the Sofa → 2000s
✅ [125] Carthage: A Survey of Punic History and Culture from Its Birth to the Final Tragedy (Great Civilizations Series) → 1980s
✅ [126] Baltimore Clipper: Its Origin and Development → 1930s
✅ [127] Devotional Treasures from the Holy Land (Second Edition) → Uncertain
✅ [128] The Book And The Map: New insights into Book of Mormon Geography → 1970s
✅ [129] Benny Goes To The Moon: The great new book from Top Children's entertainer Gerry Ogilvie (1) → 2020s
✅ [130] Small Change: A Life of Tom Waits → 1990s
✅ [131] Mae and Jane in the Rain → 2010s
✅ [132] Easy Kill (Rhona MacLeod) → 2000s
✅ [133] Backwoods Justice: An Iron Mountain Mystery → 2010s
✅ [134] Colle: Move by Move → 2010s
✅ [135] The Dinner Fix: Cooking for the Rushed → 2010s
✅ [136] Oligarchy → 2010s
✅ [137] Soul Crew Seasiders → 2000s
✅ [138] Toussaint Louverture: A Revolutionary Life → 2010s
✅ [139] The Seep → 2020s
✅ [140] If These Walls Could Talk: Calgary Flames: Stories from the Calgary Flames Ice, Locker Room, and Press Box → 2010s
✅ [141] The Jordan Tracks → 2000s
✅ [142] 2002 Volkswagen Passat Owner's Manual → 2000s
✅ [143] Forged in Blood (Freehold) → Uncertain
✅ [144] Kirsten: An American Girl : 1854 (The American Girls Collection/Boxed Set) → 1980s
✅ [145] LunaLu the Llamacorn → 2020s
✅ [146] A Walk Toward Oregon: A Memoir → 2000s
✅ [147] All Pro Dad: Seven Essentials to Be a Hero to Your Kids → 2010s
✅ [148] Trouble in the CTC!: The Terra Prime Adventures Book 2 → 2020s
✅ [149] Answers for Modern Communicators: A Guide to Effective Business Communication → 2010s
✅ [150] How Dog Food Saved the Earth → 2000s
✅ [151] Around the World Mazes → 2010s
✅ [152] The Longest Trail, Vol. 1 → 2010s
✅ [153] Jealousy → 2010s
✅ [154] Moon Phases 2021-2022 Planner: 2021 Planner, 24 Months Jan 2021 to Dec 2022, 2 Year Calendar 2021-2022 Monthly Planner → 2020s
✅ [155] From Privileges to Rights: Work and Politics in Colonial New York City (Early American Studies) → 2000s
✅ [156] 101 Media and Marketing Tips for Salon Owners, Stylists and Managers → 2000s
✅ [157] Cleo Porter and the Body Electric → 2020s
✅ [158] Capitalism, Hegemony and Violence in the Age of Drones → 2010s
✅ [159] Matchsafes: Cooper-Hewitt, National Design Museum, Smithsonian → 2000s
✅ [160] Time's Demon: BOOK II OF THE ISLEVALE CYCLE → 2010s
✅ [161] Haunted Wisconsin: Ghosts and Strange Phenomena of the Badger State (Haunted Series) → 2010s
✅ [162] Monster Kisses → 2010s
✅ [163] Marigold garden;: Pictures and rhymes, → 1880s
✅ [164] Toolbox for Sustainable City Living: A do-it-Ourselves Guide → 2000s
✅ [165] The Dark Wind CD Low Price (Jim Chee Novels) by Hillerman, Tony(April 5, 2005) Audio CD → Uncertain
✅ [166] Dead Silence → 2020s
✅ [167] Tchr Asmnt Gd Gr5 New Sci 2006 → 2000s
✅ [168] No Telephone to Heaven → Uncertain
✅ [169] Pokémon: Sun & Moon, Vol. 8 (8) → 2020s
✅ [170] Exits, Desires, & Slow Fires → 2010s
✅ [171] Six Gun Sound: The Early History of the Los Angeles County Sheriff's Department → 2000s
✅ [172] The Shadows (Guitar Legends) → 2000s
✅ [173] Victoria Magazine October 1990, Vol. 1, No. 4 → Uncertain
✅ [174] Design Innovations for Aging and Alzheimer's → 2000s
✅ [175] The Real Witches’ Garden: Spells, Herbs, Plants and Magical Spaces Outdoors → 2010s
✅ [176] Kennebago Moments → 2010s
✅ [177] Welding Symbols Quick Card (English and Ukrainian Edition) → Uncertain
✅ [178] A Cherry Cola Christmas (A Cherry Cola Book Club Novel) → 2010s
✅ [179] The Sludge → 2010s
✅ [180] Play Time (Play With Series) (Sight Word Readers) → 2000s
✅ [181] Liza of Lambeth → 2020s
✅ [182] Amazigh Arts in Morocco: Women Shaping Berber Identity → 2000s
✅ [183] The Marquess' Rose: A Regency Romance (Ladies of the North) → 2020s
✅ [184] Wasted Calories and Ruined Nights: A Journey Deeper into Dining Hell → 2010s
✅ [185] Meat Eater: Adventures from the Life of an American Hunter → 2010s
✅ [186] Consort (A Dark(ish) Faerie Tale Book 3) → 2010s
✅ [187] The Vampyre and Other Tales of the Macabre (Oxford World's Classics) → 2000s
✅ [188] Quilt Africa → 2000s
✅ [189] French Illusions: My Story as an American Au Pair in the Loire Valley → 2010s
✅ [190] Wicked Appetite (Lizzy and Diesel) → 2010s
✅ [191] Clark Weber's Rock and Roll Radio: The Fun Years, 1955-1975 → 2000s
✅ [192] Dead Famous (A Mallory Novel) → 2000s
✅ [193] The ISIS Apocalypse: The History, Strategy, and Doomsday Vision of the Islamic State → Uncertain
✅ [194] Something That Feels Like Truth (Switchgrass Books) → 2010s
✅ [195] The Secret Thoughts of an Unlikely Convert : An English Professor's Journey into Christian Faith → 2010s
✅ [196] THE ESSENTIAL GUIDE TO WRITING WELL AND GETTING PUBLISHED: Bonus Feature ~ Making Decent Dollars Writing Plus Little-Known Reward-Reaping Benefits → 2010s
✅ [197] SCUBA SHARK - Diving - Vinyl Car Decal Sticker #1329 | Vinyl Color: White → Uncertain
✅ [198] la_guerra_secreta → 2000s
✅ [199] Coleman National Forest Campground and Recreation Directory: The Only Complete Guide to All National Forest Campgrounds → 2000s
decade
2010s        82
2000s        46
2020s        21
1990s        16
Uncertain    14
1980s        11
Unknown       4
1970s         2
1930s         2
1940s         1
1880s         1
Name: count, dtype: int64

In [21]:
import sqlite3

def fetch_reviews_from_sqlite(sqlite_path):
    try:
        conn = sqlite3.connect(sqlite_path)
        query = "SELECT * FROM review"
        df_review = pd.read_sql(query, conn)
        conn.close()
        return df_review
    except Exception as e:
        print(f"❌ SQLite load failed: {e}")
        return pd.DataFrame()

# 路径按你实际位置调整
df_review = fetch_reviews_from_sqlite("../query_dataset/review_query.db")
print(f"✅ Loaded {len(df_review)} reviews")

✅ Loaded 1833 reviews

In [22]:

import json

def get_mapping_rule_from_llm(book_ids, purchase_ids, client, deployment_name):
    prompt = (
        "You are given two complete ID columns from two different datasets:\n"
        f"- The first column is `purchase_id`: {json.dumps(purchase_ids, indent=2)}\n"
        f"- The second column is `book_id`: {json.dumps(book_ids, indent=2)}\n\n"
        "Each purchase_id corresponds to a book_id, but the mapping rule is not provided.\n"
        "Your task is to determine the mapping relationship between the two sets of IDs.\n"
        "For example, is the number in `purchaseid_123` always equal to the number in `bookid_23` plus an offset?\n\n"
        "Please respond with:\n"
        "1. The exact mapping rule in plain English \n"
        "2. An explanation of why you think this rule holds."
    )

    response = client.chat.completions.create(
        model=deployment_name,
        messages=[
            {"role": "system", "content": "You are a data engineer analyzing two columns of IDs for structural relationships."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.0,
        max_tokens=500
    )

    return response.choices[0].message.content.strip()


book_ids = [b["book_id"] for b in books]
purchase_ids = df_review["purchase_id"].drop_duplicates().tolist()

mapping_rule_explanation = get_mapping_rule_from_llm(book_ids, purchase_ids, client, deployment_name)
print("🧠 GPT-inferred mapping rule:\n")
print(mapping_rule_explanation)

🧠 GPT-inferred mapping rule:

1. **Mapping Rule**: The mapping relationship between `purchase_id` and `book_id` is that the number in `purchaseid_X` corresponds to the number in `bookid_Y` where Y is equal to X. In other words, the mapping is direct and one-to-one, meaning `purchaseid_n` maps to `bookid_n` for all n from 1 to 200.

2. **Explanation**:
   - To verify this mapping rule, we can observe the structure of both ID columns. Each `purchase_id` has the format `purchaseid_X` and each `book_id` has the format `bookid_Y`, where X and Y are integers ranging from 1 to 200.
   - By examining the IDs, we can see that the numbers in both columns are sequential and cover the same range (1 to 200). This suggests a direct correspondence.
   - For example, `purchaseid_1` corresponds to `bookid_1`, `purchaseid_2` corresponds to `bookid_2`, and so on, up to `purchaseid_200` corresponding to `bookid_200`.
   - There are no gaps or offsets in the numbering, which further supports the conclusion that the mapping is straightforward and direct. Each purchase ID directly matches the book ID with the same numerical suffix.

In [23]:
def resolve_purchase_to_book_via_llm(purchase_id, mapping_rule_text, client, deployment_name):
    prompt = (
        f"The previously inferred mapping rule is:\n\n{mapping_rule_text}\n\n"
        f"Now, based on this rule, please determine the corresponding `book_id` for the following `purchase_id`:\n"
        f"- purchase_id: {purchase_id}\n\n"
        "Respond only with the `book_id`, e.g., 'bookid_88'."
    )

    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a data assistant that maps purchase IDs to book IDs using a known rule."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=20
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"❌ GPT error on {purchase_id}: {e}")
        return None

predicted_book_ids = []

for i, row in df_review.iterrows():
    purchase_id = row["purchase_id"]
    predicted_book_id = resolve_purchase_to_book_via_llm(purchase_id, mapping_rule_explanation, client, deployment_name)
    
    predicted_book_ids.append(predicted_book_id)
    print(f"[{i}] purchase_id = {purchase_id} → book_id = {predicted_book_id}")
    
df_review["book_id"] = predicted_book_ids

[0] purchase_id = purchaseid_186 → book_id = bookid_186
[1] purchase_id = purchaseid_191 → book_id = bookid_191
[2] purchase_id = purchaseid_190 → book_id = bookid_190
[3] purchase_id = purchaseid_8 → book_id = bookid_8
[4] purchase_id = purchaseid_178 → book_id = bookid_178
[5] purchase_id = purchaseid_186 → book_id = bookid_186
[6] purchase_id = purchaseid_76 → book_id = bookid_76
[7] purchase_id = purchaseid_186 → book_id = bookid_186
[8] purchase_id = purchaseid_115 → book_id = bookid_115
[9] purchase_id = purchaseid_167 → book_id = bookid_167
[10] purchase_id = purchaseid_188 → book_id = bookid_188
[11] purchase_id = purchaseid_23 → book_id = bookid_23
[12] purchase_id = purchaseid_196 → book_id = bookid_196
[13] purchase_id = purchaseid_196 → book_id = bookid_196
[14] purchase_id = purchaseid_3 → book_id = bookid_3
[15] purchase_id = purchaseid_48 → book_id = bookid_48
[16] purchase_id = purchaseid_154 → book_id = bookid_154
[17] purchase_id = purchaseid_99 → book_id = bookid_99
[18] purchase_id = purchaseid_190 → book_id = bookid_190
[19] purchase_id = purchaseid_3 → book_id = bookid_3
[20] purchase_id = purchaseid_169 → book_id = bookid_169
[21] purchase_id = purchaseid_3 → book_id = bookid_3
[22] purchase_id = purchaseid_145 → book_id = bookid_145
[23] purchase_id = purchaseid_194 → book_id = bookid_194
[24] purchase_id = purchaseid_81 → book_id = bookid_81
[25] purchase_id = purchaseid_199 → book_id = bookid_199
[26] purchase_id = purchaseid_48 → book_id = bookid_48
[27] purchase_id = purchaseid_96 → book_id = bookid_96
[28] purchase_id = purchaseid_167 → book_id = bookid_167
[29] purchase_id = purchaseid_196 → book_id = bookid_196
[30] purchase_id = purchaseid_196 → book_id = bookid_196
[31] purchase_id = purchaseid_196 → book_id = bookid_196
[32] purchase_id = purchaseid_148 → book_id = bookid_148
[33] purchase_id = purchaseid_8 → book_id = bookid_8
[34] purchase_id = purchaseid_145 → book_id = bookid_145
[35] purchase_id = purchaseid_200 → book_id = bookid_200
[36] purchase_id = purchaseid_8 → book_id = bookid_8
[37] purchase_id = purchaseid_178 → book_id = bookid_178
[38] purchase_id = purchaseid_20 → book_id = bookid_20
[39] purchase_id = purchaseid_52 → book_id = bookid_52
[40] purchase_id = purchaseid_159 → book_id = bookid_159
[41] purchase_id = purchaseid_83 → book_id = bookid_83
[42] purchase_id = purchaseid_67 → book_id = bookid_67
[43] purchase_id = purchaseid_3 → book_id = bookid_3
[44] purchase_id = purchaseid_58 → book_id = bookid_58
[45] purchase_id = purchaseid_196 → book_id = bookid_196
[46] purchase_id = purchaseid_95 → book_id = bookid_95
[47] purchase_id = purchaseid_76 → book_id = bookid_76
[48] purchase_id = purchaseid_3 → book_id = bookid_3
[49] purchase_id = purchaseid_62 → book_id = bookid_62
[50] purchase_id = purchaseid_136 → book_id = bookid_136
[51] purchase_id = purchaseid_10 → book_id = bookid_10
[52] purchase_id = purchaseid_3 → book_id = bookid_3
[53] purchase_id = purchaseid_10 → book_id = bookid_10
[54] purchase_id = purchaseid_3 → book_id = bookid_3
[55] purchase_id = purchaseid_186 → book_id = bookid_186
[56] purchase_id = purchaseid_46 → book_id = bookid_46
[57] purchase_id = purchaseid_38 → book_id = bookid_38
[58] purchase_id = purchaseid_145 → book_id = bookid_145
[59] purchase_id = purchaseid_48 → book_id = bookid_48
[60] purchase_id = purchaseid_10 → book_id = bookid_10
[61] purchase_id = purchaseid_31 → book_id = bookid_31
[62] purchase_id = purchaseid_115 → book_id = bookid_115
[63] purchase_id = purchaseid_48 → book_id = bookid_48
[64] purchase_id = purchaseid_196 → book_id = bookid_196
[65] purchase_id = purchaseid_178 → book_id = bookid_178
[66] purchase_id = purchaseid_7 → book_id = bookid_7
[67] purchase_id = purchaseid_4 → book_id = bookid_4
[68] purchase_id = purchaseid_104 → book_id = bookid_104
[69] purchase_id = purchaseid_8 → book_id = bookid_8
[70] purchase_id = purchaseid_162 → book_id = bookid_162
[71] purchase_id = purchaseid_145 → book_id = bookid_145
[72] purchase_id = purchaseid_8 → book_id = bookid_8
[73] purchase_id = purchaseid_3 → book_id = bookid_3
[74] purchase_id = purchaseid_186 → book_id = bookid_186
[75] purchase_id = purchaseid_5 → book_id = bookid_5
[76] purchase_id = purchaseid_20 → book_id = bookid_20
[77] purchase_id = purchaseid_158 → book_id = bookid_158
[78] purchase_id = purchaseid_8 → book_id = bookid_8
[79] purchase_id = purchaseid_165 → book_id = bookid_165
[80] purchase_id = purchaseid_8 → book_id = bookid_8
[81] purchase_id = purchaseid_6 → book_id = bookid_6
[82] purchase_id = purchaseid_158 → book_id = bookid_158
[83] purchase_id = purchaseid_196 → book_id = bookid_196
[84] purchase_id = purchaseid_5 → book_id = bookid_5
[85] purchase_id = purchaseid_8 → book_id = bookid_8
[86] purchase_id = purchaseid_115 → book_id = bookid_115
[87] purchase_id = purchaseid_46 → book_id = bookid_46
[88] purchase_id = purchaseid_83 → book_id = bookid_83
[89] purchase_id = purchaseid_86 → book_id = bookid_86
[90] purchase_id = purchaseid_174 → book_id = bookid_174
[91] purchase_id = purchaseid_178 → book_id = bookid_178
[92] purchase_id = purchaseid_8 → book_id = bookid_8
[93] purchase_id = purchaseid_48 → book_id = bookid_48
[94] purchase_id = purchaseid_8 → book_id = bookid_8
[95] purchase_id = purchaseid_3 → book_id = bookid_3
[96] purchase_id = purchaseid_3 → book_id = bookid_3
[97] purchase_id = purchaseid_177 → book_id = bookid_177
[98] purchase_id = purchaseid_187 → book_id = bookid_187
[99] purchase_id = purchaseid_188 → book_id = bookid_188
[100] purchase_id = purchaseid_8 → book_id = bookid_8
[101] purchase_id = purchaseid_63 → book_id = bookid_63
[102] purchase_id = purchaseid_33 → book_id = bookid_33
[103] purchase_id = purchaseid_178 → book_id = bookid_178
[104] purchase_id = purchaseid_178 → book_id = bookid_178
[105] purchase_id = purchaseid_178 → book_id = bookid_178
[106] purchase_id = purchaseid_62 → book_id = bookid_62
[107] purchase_id = purchaseid_10 → book_id = bookid_10
[108] purchase_id = purchaseid_48 → book_id = bookid_48
[109] purchase_id = purchaseid_8 → book_id = bookid_8
[110] purchase_id = purchaseid_62 → book_id = bookid_62
[111] purchase_id = purchaseid_178 → book_id = bookid_178
[112] purchase_id = purchaseid_32 → book_id = bookid_32
[113] purchase_id = purchaseid_157 → book_id = bookid_157
[114] purchase_id = purchaseid_193 → book_id = bookid_193
[115] purchase_id = purchaseid_196 → book_id = bookid_196
[116] purchase_id = purchaseid_186 → book_id = bookid_186
[117] purchase_id = purchaseid_185 → book_id = bookid_185
[118] purchase_id = purchaseid_178 → book_id = bookid_178
[119] purchase_id = purchaseid_187 → book_id = bookid_187
[120] purchase_id = purchaseid_178 → book_id = bookid_178
[121] purchase_id = purchaseid_196 → book_id = bookid_196
[122] purchase_id = purchaseid_13 → book_id = bookid_13
[123] purchase_id = purchaseid_3 → book_id = bookid_3
[124] purchase_id = purchaseid_72 → book_id = bookid_72
[125] purchase_id = purchaseid_196 → book_id = bookid_196
[126] purchase_id = purchaseid_42 → book_id = bookid_42
[127] purchase_id = purchaseid_96 → book_id = bookid_96
[128] purchase_id = purchaseid_73 → book_id = bookid_73
[129] purchase_id = purchaseid_188 → book_id = bookid_188
[130] purchase_id = purchaseid_145 → book_id = bookid_145
[131] purchase_id = purchaseid_97 → book_id = bookid_97
[132] purchase_id = purchaseid_59 → book_id = bookid_59
[133] purchase_id = purchaseid_192 → book_id = bookid_192
[134] purchase_id = purchaseid_178 → book_id = bookid_178
[135] purchase_id = purchaseid_193 → book_id = bookid_193
[136] purchase_id = purchaseid_8 → book_id = bookid_8
[137] purchase_id = purchaseid_178 → book_id = bookid_178
[138] purchase_id = purchaseid_109 → book_id = bookid_109
[139] purchase_id = purchaseid_3 → book_id = bookid_3
[140] purchase_id = purchaseid_99 → book_id = bookid_99
[141] purchase_id = purchaseid_76 → book_id = bookid_76
[142] purchase_id = purchaseid_3 → book_id = bookid_3
[143] purchase_id = purchaseid_8 → book_id = bookid_8
[144] purchase_id = purchaseid_3 → book_id = bookid_3
[145] purchase_id = purchaseid_154 → book_id = bookid_154
[146] purchase_id = purchaseid_148 → book_id = bookid_148
[147] purchase_id = purchaseid_178 → book_id = bookid_178
[148] purchase_id = purchaseid_163 → book_id = bookid_163
[149] purchase_id = purchaseid_178 → book_id = bookid_178
[150] purchase_id = purchaseid_178 → book_id = bookid_178
[151] purchase_id = purchaseid_178 → book_id = bookid_178
[152] purchase_id = purchaseid_52 → book_id = bookid_52
[153] purchase_id = purchaseid_109 → book_id = bookid_109
[154] purchase_id = purchaseid_196 → book_id = bookid_196
[155] purchase_id = purchaseid_196 → book_id = bookid_196
[156] purchase_id = purchaseid_106 → book_id = bookid_106
[157] purchase_id = purchaseid_130 → book_id = bookid_130
[158] purchase_id = purchaseid_118 → book_id = bookid_118
[159] purchase_id = purchaseid_167 → book_id = bookid_167
[160] purchase_id = purchaseid_8 → book_id = bookid_8
[161] purchase_id = purchaseid_103 → book_id = bookid_103
[162] purchase_id = purchaseid_8 → book_id = bookid_8
[163] purchase_id = purchaseid_5 → book_id = bookid_5
[164] purchase_id = purchaseid_8 → book_id = bookid_8
[165] purchase_id = purchaseid_103 → book_id = bookid_103
[166] purchase_id = purchaseid_5 → book_id = bookid_5
[167] purchase_id = purchaseid_3 → book_id = bookid_3
[168] purchase_id = purchaseid_20 → book_id = bookid_20
[169] purchase_id = purchaseid_3 → book_id = bookid_3
[170] purchase_id = purchaseid_8 → book_id = bookid_8
[171] purchase_id = purchaseid_8 → book_id = bookid_8
[172] purchase_id = purchaseid_178 → book_id = bookid_178
[173] purchase_id = purchaseid_178 → book_id = bookid_178
[174] purchase_id = purchaseid_115 → book_id = bookid_115
[175] purchase_id = purchaseid_3 → book_id = bookid_3
[176] purchase_id = purchaseid_8 → book_id = bookid_8
[177] purchase_id = purchaseid_154 → book_id = bookid_154
[178] purchase_id = purchaseid_8 → book_id = bookid_8
[179] purchase_id = purchaseid_154 → book_id = bookid_154
[180] purchase_id = purchaseid_32 → book_id = bookid_32
[181] purchase_id = purchaseid_186 → book_id = bookid_186
[182] purchase_id = purchaseid_161 → book_id = bookid_161
[183] purchase_id = purchaseid_41 → book_id = bookid_41
[184] purchase_id = purchaseid_36 → book_id = bookid_36
[185] purchase_id = purchaseid_145 → book_id = bookid_145
[186] purchase_id = purchaseid_196 → book_id = bookid_196
[187] purchase_id = purchaseid_8 → book_id = bookid_8
[188] purchase_id = purchaseid_145 → book_id = bookid_145
[189] purchase_id = purchaseid_20 → book_id = bookid_20
[190] purchase_id = purchaseid_124 → book_id = bookid_124
[191] purchase_id = purchaseid_48 → book_id = bookid_48
[192] purchase_id = purchaseid_32 → book_id = bookid_32
[193] purchase_id = purchaseid_196 → book_id = bookid_196
[194] purchase_id = purchaseid_3 → book_id = bookid_3
[195] purchase_id = purchaseid_148 → book_id = bookid_148
[196] purchase_id = purchaseid_196 → book_id = bookid_196
[197] purchase_id = purchaseid_197 → book_id = bookid_197
[198] purchase_id = purchaseid_196 → book_id = bookid_196
[199] purchase_id = purchaseid_41 → book_id = bookid_41
[200] purchase_id = purchaseid_196 → book_id = bookid_196
[201] purchase_id = purchaseid_178 → book_id = bookid_178
[202] purchase_id = purchaseid_173 → book_id = bookid_173
[203] purchase_id = purchaseid_178 → book_id = bookid_178
[204] purchase_id = purchaseid_5 → book_id = bookid_5
[205] purchase_id = purchaseid_8 → book_id = bookid_8
[206] purchase_id = purchaseid_83 → book_id = bookid_83
[207] purchase_id = purchaseid_178 → book_id = bookid_178
[208] purchase_id = purchaseid_8 → book_id = bookid_8
[209] purchase_id = purchaseid_5 → book_id = bookid_5
[210] purchase_id = purchaseid_12 → book_id = bookid_12
[211] purchase_id = purchaseid_3 → book_id = bookid_3
[212] purchase_id = purchaseid_8 → book_id = bookid_8
[213] purchase_id = purchaseid_46 → book_id = bookid_46
[214] purchase_id = purchaseid_140 → book_id = bookid_140
[215] purchase_id = purchaseid_72 → book_id = bookid_72
[216] purchase_id = purchaseid_120 → book_id = bookid_120
[217] purchase_id = purchaseid_8 → book_id = bookid_8
[218] purchase_id = purchaseid_166 → book_id = bookid_166
[219] purchase_id = purchaseid_178 → book_id = bookid_178
[220] purchase_id = purchaseid_196 → book_id = bookid_196
[221] purchase_id = purchaseid_8 → book_id = bookid_8
[222] purchase_id = purchaseid_85 → book_id = bookid_85
[223] purchase_id = purchaseid_94 → book_id = bookid_94
[224] purchase_id = purchaseid_72 → book_id = bookid_72
[225] purchase_id = purchaseid_178 → book_id = bookid_178
[226] purchase_id = purchaseid_194 → book_id = bookid_194
[227] purchase_id = purchaseid_186 → book_id = bookid_186
[228] purchase_id = purchaseid_145 → book_id = bookid_145
[229] purchase_id = purchaseid_3 → book_id = bookid_3
[230] purchase_id = purchaseid_187 → book_id = bookid_187
[231] purchase_id = purchaseid_8 → book_id = bookid_8
[232] purchase_id = purchaseid_72 → book_id = bookid_72
[233] purchase_id = purchaseid_48 → book_id = bookid_48
[234] purchase_id = purchaseid_90 → book_id = bookid_90
[235] purchase_id = purchaseid_186 → book_id = bookid_186
[236] purchase_id = purchaseid_133 → book_id = bookid_133
[237] purchase_id = purchaseid_160 → book_id = bookid_160
[238] purchase_id = purchaseid_20 → book_id = bookid_20
[239] purchase_id = purchaseid_148 → book_id = bookid_148
[240] purchase_id = purchaseid_62 → book_id = bookid_62
[241] purchase_id = purchaseid_161 → book_id = bookid_161
[242] purchase_id = purchaseid_8 → book_id = bookid_8
[243] purchase_id = purchaseid_62 → book_id = bookid_62
[244] purchase_id = purchaseid_178 → book_id = bookid_178
[245] purchase_id = purchaseid_181 → book_id = bookid_181
[246] purchase_id = purchaseid_186 → book_id = bookid_186
[247] purchase_id = purchaseid_8 → book_id = bookid_8
[248] purchase_id = purchaseid_8 → book_id = bookid_8
[249] purchase_id = purchaseid_145 → book_id = bookid_145
[250] purchase_id = purchaseid_131 → book_id = bookid_131
[251] purchase_id = purchaseid_185 → book_id = bookid_185
[252] purchase_id = purchaseid_195 → book_id = bookid_195
[253] purchase_id = purchaseid_186 → book_id = bookid_186
[254] purchase_id = purchaseid_113 → book_id = bookid_113
[255] purchase_id = purchaseid_129 → book_id = bookid_129
[256] purchase_id = purchaseid_190 → book_id = bookid_190
[257] purchase_id = purchaseid_196 → book_id = bookid_196
[258] purchase_id = purchaseid_46 → book_id = bookid_46
[259] purchase_id = purchaseid_154 → book_id = bookid_154
[260] purchase_id = purchaseid_10 → book_id = bookid_10
[261] purchase_id = purchaseid_3 → book_id = bookid_3
[262] purchase_id = purchaseid_48 → book_id = bookid_48
[263] purchase_id = purchaseid_20 → book_id = bookid_20
[264] purchase_id = purchaseid_62 → book_id = bookid_62
[265] purchase_id = purchaseid_84 → book_id = bookid_84
[266] purchase_id = purchaseid_20 → book_id = bookid_20
[267] purchase_id = purchaseid_32 → book_id = bookid_32
[268] purchase_id = purchaseid_196 → book_id = bookid_196
[269] purchase_id = purchaseid_8 → book_id = bookid_8
[270] purchase_id = purchaseid_20 → book_id = bookid_20
[271] purchase_id = purchaseid_76 → book_id = bookid_76
[272] purchase_id = purchaseid_170 → book_id = bookid_170
[273] purchase_id = purchaseid_178 → book_id = bookid_178
[274] purchase_id = purchaseid_53 → book_id = bookid_53
[275] purchase_id = purchaseid_178 → book_id = bookid_178
[276] purchase_id = purchaseid_141 → book_id = bookid_141
[277] purchase_id = purchaseid_62 → book_id = bookid_62
[278] purchase_id = purchaseid_186 → book_id = bookid_186
[279] purchase_id = purchaseid_186 → book_id = bookid_186
[280] purchase_id = purchaseid_186 → book_id = bookid_186
[281] purchase_id = purchaseid_186 → book_id = bookid_186
[282] purchase_id = purchaseid_186 → book_id = bookid_186
[283] purchase_id = purchaseid_186 → book_id = bookid_186
[284] purchase_id = purchaseid_186 → book_id = bookid_186
[285] purchase_id = purchaseid_186 → book_id = bookid_186
[286] purchase_id = purchaseid_186 → book_id = bookid_186
[287] purchase_id = purchaseid_186 → book_id = bookid_186
[288] purchase_id = purchaseid_186 → book_id = bookid_186
[289] purchase_id = purchaseid_186 → book_id = bookid_186
[290] purchase_id = purchaseid_8 → book_id = bookid_8
[291] purchase_id = purchaseid_137 → book_id = bookid_137
[292] purchase_id = purchaseid_72 → book_id = bookid_72
[293] purchase_id = purchaseid_115 → book_id = bookid_115
[294] purchase_id = purchaseid_8 → book_id = bookid_8
[295] purchase_id = purchaseid_186 → book_id = bookid_186
[296] purchase_id = purchaseid_178 → book_id = bookid_178
[297] purchase_id = purchaseid_178 → book_id = bookid_178
[298] purchase_id = purchaseid_167 → book_id = bookid_167
[299] purchase_id = purchaseid_23 → book_id = bookid_23
[300] purchase_id = purchaseid_167 → book_id = bookid_167
[301] purchase_id = purchaseid_67 → book_id = bookid_67
[302] purchase_id = purchaseid_99 → book_id = bookid_99
[303] purchase_id = purchaseid_198 → book_id = bookid_198
[304] purchase_id = purchaseid_95 → book_id = bookid_95
[305] purchase_id = purchaseid_8 → book_id = bookid_8
[306] purchase_id = purchaseid_83 → book_id = bookid_83
[307] purchase_id = purchaseid_196 → book_id = bookid_196
[308] purchase_id = purchaseid_178 → book_id = bookid_178
[309] purchase_id = purchaseid_3 → book_id = bookid_3
[310] purchase_id = purchaseid_8 → book_id = bookid_8
[311] purchase_id = purchaseid_129 → book_id = bookid_129
[312] purchase_id = purchaseid_3 → book_id = bookid_3
[313] purchase_id = purchaseid_178 → book_id = bookid_178
[314] purchase_id = purchaseid_3 → book_id = bookid_3
[315] purchase_id = purchaseid_3 → book_id = bookid_3
[316] purchase_id = purchaseid_58 → book_id = bookid_58
[317] purchase_id = purchaseid_178 → book_id = bookid_178
[318] purchase_id = purchaseid_186 → book_id = bookid_186
[319] purchase_id = purchaseid_94 → book_id = bookid_94
[320] purchase_id = purchaseid_20 → book_id = bookid_20
[321] purchase_id = purchaseid_125 → book_id = bookid_125
[322] purchase_id = purchaseid_10 → book_id = bookid_10
[323] purchase_id = purchaseid_158 → book_id = bookid_158
[324] purchase_id = purchaseid_38 → book_id = bookid_38
[325] purchase_id = purchaseid_129 → book_id = bookid_129
[326] purchase_id = purchaseid_28 → book_id = bookid_28
[327] purchase_id = purchaseid_8 → book_id = bookid_8
[328] purchase_id = purchaseid_52 → book_id = bookid_52
[329] purchase_id = purchaseid_8 → book_id = bookid_8
[330] purchase_id = purchaseid_178 → book_id = bookid_178
[331] purchase_id = purchaseid_5 → book_id = bookid_5
[332] purchase_id = purchaseid_196 → book_id = bookid_196
[333] purchase_id = purchaseid_8 → book_id = bookid_8
[334] purchase_id = purchaseid_193 → book_id = bookid_193
[335] purchase_id = purchaseid_8 → book_id = bookid_8
[336] purchase_id = purchaseid_8 → book_id = bookid_8
[337] purchase_id = purchaseid_169 → book_id = bookid_169
[338] purchase_id = purchaseid_178 → book_id = bookid_178
[339] purchase_id = purchaseid_3 → book_id = bookid_3
[340] purchase_id = purchaseid_3 → book_id = bookid_3
[341] purchase_id = purchaseid_21 → book_id = bookid_21
[342] purchase_id = purchaseid_5 → book_id = bookid_5
[343] purchase_id = purchaseid_194 → book_id = bookid_194
[344] purchase_id = purchaseid_193 → book_id = bookid_193
[345] purchase_id = purchaseid_119 → book_id = bookid_119
[346] purchase_id = purchaseid_35 → book_id = bookid_35
[347] purchase_id = purchaseid_148 → book_id = bookid_148
[348] purchase_id = purchaseid_196 → book_id = bookid_196
[349] purchase_id = purchaseid_196 → book_id = bookid_196
[350] purchase_id = purchaseid_106 → book_id = bookid_106
[351] purchase_id = purchaseid_63 → book_id = bookid_63
[352] purchase_id = purchaseid_154 → book_id = bookid_154
[353] purchase_id = purchaseid_154 → book_id = bookid_154
[354] purchase_id = purchaseid_196 → book_id = bookid_196

In [24]:
import pandas as pd

# === Step 1: 将每条 review 映射到对应 decade ===
df_review["decade"] = df_review["book_id"].map(book_id_to_decade)

# === Step 2: 清洗无效值 ===
df_review["rating"] = pd.to_numeric(df_review["rating"], errors="coerce")
df_review = df_review[df_review["rating"].notnull()]
df_review = df_review[df_review["decade"].notnull() & (df_review["decade"] != "Unknown")]

# === Step 3: 按 decade 聚合，统计每个 decade 的平均评分和不同 book 数量 ===
df_result = (
    df_review.groupby("decade")
    .agg(
        num_books=("book_id", "nunique"),
        avg_rating=("rating", "mean")
    )
    .reset_index()
)

# === Step 4: 只保留包含 ≥10 本书的 decade ===
df_filtered = df_result[df_result["num_books"] >= 10]

# === Step 5: 找出平均评分最高的 decade ===
top_decade = df_filtered.sort_values(by="avg_rating", ascending=False).head(1)

# === Step 6: 输出结果 ===
print("📊 Aggregated results by decade (≥10 distinct books):")
display(df_filtered.sort_values(by="avg_rating", ascending=False))

print("\n🏆 Top-rated decade:")
display(top_decade)

📊 Aggregated results by decade (≥10 distinct books):

      decade  num_books  avg_rating
8      2020s         21    4.663636
9  Uncertain         14    4.611429
7      2010s         82    4.602170
6      2000s         46    4.273684
4      1980s         11    4.208333
5      1990s         16    3.779661

🏆 Top-rated decade:

  decade  num_books  avg_rating
8  2020s         21    4.663636

In [25]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine
from openai import AzureOpenAI
# MySQL配置
mysql_password = "20041025"  # 替换为你的MySQL密码
mysql_db = "ucb_db"
mysql_table = "books_info"

# ========== Configuration ========== #
client = AzureOpenAI(
    api_key="609ced4d971240b8a08f7fb0e6d846ea",
    api_version="2024-08-01-preview",
    azure_endpoint="https://promptdelta-nc.openai.azure.com",  # 不要加 /v1
)
deployment_name = "gpt-4o-mini" 

def fetch_business_data():
    try:
        conn = mysql.connector.connect(
            host="localhost",
            user="root",
            password=mysql_password,
            database=mysql_db
        )
        cursor = conn.cursor()
        cursor.execute(f"SELECT * FROM {mysql_table}")
        column_names = [desc[0] for desc in cursor.description]
        rows = cursor.fetchall()
        conn.close()
        return rows, column_names
    except Exception as e:
        print(f"❌ MySQL connection failed: {e}")
        return [], []

rows, column_names = fetch_business_data()
books = [dict(zip(column_names, row)) for row in rows]
print(f"✅ Total {len(books)} books")

def is_qualified_book(details, categories, client, deployment_name):
    prompt = (
        "You're given a book's description and category field.\n"
        "Determine if this book is written in English and belongs to the 'Literature & Fiction' category.\n\n"
        "If both conditions are true, answer with 'yes'. If either is false, answer with 'no'.\n\n"
        f"Description:\n{details}\n\n"
        f"Categories:\n{categories}\n\n"
        "Just answer 'yes' or 'no'.\n\n"
    )
    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a helpful assistant that filters books by language and category."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=5
        )
        return response.choices[0].message.content.strip().lower() == "yes"
    except Exception as e:
        print(f"❌ GPT error: {e}")
        return False

qualified_books = []

for i, book in enumerate(books):
    details = book.get("details", "")
    categories = book.get("categories", "")
    if not details.strip():
        print(f"❌ [{i}] No details")
        continue

    is_qualified = is_qualified_book(details, categories, client, deployment_name)
    if is_qualified:
        qualified_books.append(book)
        print(f"✅ [{i}] Matched: {book.get('title', 'Untitled')}, {categories}, {details}")
    else:
        print(f"❌ [{i}] Not matched")

df_qualified = pd.DataFrame(qualified_books)
print(f"\n Retained {len(df_qualified)} English Literature & Fiction books")

✅ Total 200 books
✅ [0] Matched: Chaucer, ["Books", "Literature & Fiction", "History & Criticism"], Published by Chatto & Windus, the first edition of this book was released on January 1, 2004. It is written in English and comes in a hardcover format, comprising 196 pages. The book has an ISBN-10 of 0701169850 and an ISBN-13 of 978-0701169855. Weighing 10.1 ounces, its dimensions are 5.39 x 0.71 x 7.48 inches.
❌ [1] Not matched
❌ [2] Not matched
❌ [3] Not matched
❌ [4] Not matched
❌ [5] Not matched
❌ [6] Not matched
❌ [7] Not matched
✅ [8] Matched: Reunion: The Children of Lauderdale Park, ["Books", "Literature & Fiction", "Genre Fiction"], This book, published independently on September 25, 2019, is written in English and spans 367 pages. It is available in paperback format and has an ISBN-10 of 1694621731 and an ISBN-13 of 978-1694621733. The item weighs 1.38 pounds and measures 6 x 0.92 x 9 inches.
❌ [9] Not matched
❌ [10] Not matched
❌ [11] Not matched
✅ [12] Matched: Girl Made of Glass, ["Books", "Literature & Fiction", "Poetry"], The book, published by Central Avenue Publishing on January 24, 2023, is available in English and comes in paperback format, consisting of 144 pages. It has an ISBN-10 number of 1771682760 and an ISBN-13 number of 978-1771682763. The item weighs 5.1 ounces and has dimensions of 5.25 x 0.4 x 8 inches.
❌ [13] Not matched
❌ [14] Not matched
❌ [15] Not matched
❌ [16] Not matched
❌ [17] Not matched
❌ [18] Not matched
❌ [19] Not matched
❌ [20] Not matched
❌ [21] Not matched
❌ [22] Not matched
❌ [23] Not matched
❌ [24] Not matched
❌ [25] Not matched
❌ [26] Not matched
❌ [27] Not matched
❌ [28] Not matched
✅ [29] Matched: Sugary Sweets (A Taste of Love Series), ["Books", "Literature & Fiction", "Humor & Satire"], This book, published by CreateSpace Independent Publishing Platform on August 18, 2016, is written in English and is available in paperback, consisting of 140 pages. It has an ISBN-10 of 1536832286 and an ISBN-13 of 978-1536832280. The item weighs 6.6 ounces and its dimensions are 5.51 x 0.33 x 8.5 inches.
❌ [30] Not matched
❌ [31] Not matched
❌ [32] Not matched
❌ [33] Not matched
❌ [34] Not matched
✅ [35] Matched: Therapy Mammals, ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by Rare Bird Books as part of the Barnacle Books series on June 12, 2018, is written in English and consists of 376 pages. It has an ISBN-10 of 194557299X and an ISBN-13 of 978-1945572999. Weighing 12.8 ounces, its dimensions are 5.5 x 1 x 8.5 inches.
✅ [36] Matched: A Most Dangerous Book: Tacitus's Germania from the Roman Empire to the Third Reich, ["Books", "Literature & Fiction", "History & Criticism"], This illustrated edition, published by W. W. Norton & Company on May 2, 2011, is available in English and features a hardcover format comprising 304 pages. The book has an ISBN-10 of 0393062651 and an ISBN-13 of 978-0393062656. It weighs 1.03 pounds and has dimensions of 5.8 x 1.1 x 8.6 inches.
✅ [37] Matched: The Prophet: With Original 1923 Illustrations by the Author, ["Books", "Literature & Fiction", "Poetry"], The book, published by Suzeteo Enterprises on February 14, 2019, is available in English and consists of 48 pages. It has an ISBN-10 of 1947844938 and an ISBN-13 of 978-1947844933. The Lexile measure for this book is 990L. Weighing 2.08 ounces, its dimensions are 5 inches in width, 0.1 inches in thickness, and 8 inches in height.
✅ [38] Matched: The Melancholy Strumpet Master, ["Books", "Literature & Fiction", "Humor & Satire"], This book, published independently on February 19, 2023, is written in English and spans 257 pages in paperback format. It has an ISBN 13 of 979-8378201969 and weighs 14.1 ounces. The dimensions of the book are 5.5 x 0.65 x 8.5 inches.
❌ [39] Not matched
❌ [40] Not matched
❌ [41] Not matched
❌ [42] Not matched
✅ [43] Matched: Reptilian, ["Books", "Literature & Fiction", "Genre Fiction"], This book was published on January 2, 2019, and is available in English. The file size is 1532 KB, and it allows for unlimited simultaneous device usage. Text-to-speech functionality is enabled, and it supports screen readers. Enhanced typesetting is also enabled, while the X-Ray feature is not available. Word Wise is activated, and sticky notes can be used on Kindle Scribe. The print length of the book is 201 pages.
❌ [44] Not matched
❌ [45] Not matched
❌ [46] Not matched
❌ [47] Not matched
✅ [48] Matched: Primeval: A Journal of the Uncanny - Issue #1, ["Books", "Literature & Fiction", "History & Criticism"], This book, published by Blood Bound Books in its Issue #1 edition on August 31, 2013, is available in English and comprises 102 pages. It has an ISBN-10 number of 1940250064 and an ISBN-13 number of 978-1940250069. The item weighs 5 ounces and its dimensions are 5.5 x 0.24 x 8.5 inches.
❌ [49] Not matched
❌ [50] Not matched
❌ [51] Not matched
❌ [52] Not matched
❌ [53] Not matched
✅ [54] Matched: Behind the Wheel (Choose Your Own Adventure #35)(Paperback/Revised), ["Books", "Children's Books", "Literature & Fiction"], This illustrated edition, published by Chooseco on August 1, 2010, is written in English and consists of 144 pages. It has an ISBN-10 number of 1933390352 and an ISBN-13 number of 978-1933390352. The book is suitable for readers aged 8 to 12 years, with a Lexile measure of 700L, making it appropriate for students in grades 4 to 8. Weighing 3.68 ounces, the book has dimensions of 4.28 x 0.39 x 6.9 inches.
❌ [55] Not matched
❌ [56] Not matched
❌ [57] Not matched
❌ [58] Not matched
❌ [59] Not matched
❌ [60] Not matched
❌ [61] Not matched
❌ [62] Not matched
❌ [63] Not matched
❌ [64] Not matched
❌ [65] Not matched
❌ [66] Not matched
❌ [67] Not matched
✅ [68] Matched: Out of Sheer Rage: Wrestling with D. H. Lawrence, ["Books", "Literature & Fiction", "History & Criticism"], This book, published by Picador on November 10, 2009, is available in English and consists of 256 pages. It has an ISBN-10 of 0312429460 and an ISBN-13 of 978-0312429461. The item weighs 8 ounces and features dimensions of 5.56 x 0.69 x 8.27 inches.
✅ [69] Matched: Polly and the Shadow Goblin: Book 2, Mother of Witches, ["Books", "Literature & Fiction", "Mythology & Folk Tales"], This illustrated edition, published by XLIBRIS on March 17, 2014, is available in English and is presented in a paperback format comprising 114 pages. The book has an ISBN-10 of 1493183265 and an ISBN-13 of 978-1493183265. It weighs 6.2 ounces and measures 6 x 0.29 x 9 inches.
❌ [70] Not matched
❌ [71] Not matched
❌ [72] Not matched
✅ [73] Matched: Child Of The King A Journey of Hope Book 1: Earthly Story With A Heavenly Message, ["Books", "Literature & Fiction"], This book, published by Self Publishing on December 1, 2022, is written in English and comprises 192 pages. It has an ISBN 13 of 979-8887592497 and weighs 8.8 ounces. The dimensions of the book are 5.5 by 0.48 by 8.5 inches.
❌ [74] Not matched
❌ [75] Not matched
✅ [76] Matched: One September Morning, ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by Kensington on January 1, 2009, is written in English and is available in paperback, consisting of 448 pages. It has an ISBN-10 of 0758209290 and an ISBN-13 of 978-0758209290. The item weighs 13.4 ounces and its dimensions are 5.5 x 1.13 x 8.5 inches.
❌ [77] Not matched
❌ [78] Not matched
❌ [79] Not matched
❌ [80] Not matched
✅ [81] Matched: Fire Cracker, ["Books", "Literature & Fiction", "United States"], This book, published by Kensington on July 1, 1997, is available in English and features a paperback format with a total of 312 pages. It has an ISBN-10 of 1575661810 and an ISBN-13 of 978-1575661810. The item weighs 1.3 pounds and its dimensions are 6.25 inches in width, 1.25 inches in thickness, and 9.5 inches in height.
❌ [82] Not matched
✅ [83] Matched: Local Honey, ["Books", "Literature & Fiction"], This book, published by Xlibris on June 26, 2015, is written in English and spans 166 pages in paperback format. It has an ISBN 10 of 1503581098 and an ISBN 13 of 978-1503581098. The item weighs 8.8 ounces and has dimensions of 6 x 0.42 x 9 inches.
❌ [84] Not matched
❌ [85] Not matched
❌ [86] Not matched
❌ [87] Not matched
✅ [88] Matched: I'll Ride For My Hood: A Salty Love Story, ["Books", "Literature & Fiction", "Dramas & Plays"], This book, published by Alana's Book Line in its first edition on January 5, 2016, is available in English and has a file size of 3177 KB. It features Text to Speech and is compatible with screen readers, while enhanced typesetting is also enabled. However, X Ray and Word Wise functionalities are not available. Readers can make sticky notes using Kindle Scribe, and the book has a print length of 216 pages.
❌ [89] No details
❌ [90] Not matched
✅ [91] Matched: Outage, ["Books", "Literature & Fiction", "Genre Fiction"], The book, published by CreateSpace Independent Publishing Platform on June 25, 2014, is written in English and features a paperback format with a total of 122 pages. It has an ISBN-10 of 1500256897 and an ISBN-13 of 978-1500256890. Weighing 6.1 ounces, the book measures 6 x 0.28 x 9 inches.
✅ [92] Matched: Simantov, ["Books", "Literature & Fiction", "Genre Fiction"], Published by Angry Robot on April 14, 2020, this book is available in English and has a file size of 3940 KB. It supports Text to Speech and is compatible with screen readers, enhancing accessibility for all readers. The book features enhanced typesetting and includes X-Ray and Word Wise functionalities to enrich the reading experience. Additionally, sticky notes can be utilized on Kindle Scribe. The print length of the book is 392 pages.
❌ [93] Not matched
❌ [94] Not matched
❌ [95] Not matched
❌ [96] Not matched
✅ [97] Matched: Hollywood Confessions: Hollywood Headlines Book #3 (Hollywood Headlines Mysteries), ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by CreateSpace Independent Publishing Platform on May 31, 2011, is written in English and features a paperback format consisting of 209 pages. It has an ISBN 10 number of 1463534795 and an ISBN 13 number of 978-1463534790. The item weighs 7.8 ounces and has dimensions of 5.25 x 0.48 x 8 inches.
✅ [98] Matched: Buddy the Soldier Bear, ["Books", "Children's Books", "Literature & Fiction"], The book, published by RJ Henry Publishing in its first edition on January 5, 2017, is written in English and is available in paperback format, consisting of 31 pages. It has an ISBN-10 of 099792490X and an ISBN-13 of 978-0997924909. The item weighs 3.52 ounces and measures 8.5 x 0.08 x 8.5 inches.
❌ [99] Not matched
✅ [100] Matched: Knowing When To Die: Uncollected Stories, ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by Independent Legions Publishing in its first edition on June 19, 2018, is written in English and spans 216 pages. It is available in paperback and has an ISBN-10 of 8831959018 and an ISBN-13 of 978-8831959018. The item weighs 9.9 ounces and has dimensions of 5.5 x 0.54 x 8.5 inches.
❌ [101] Not matched
❌ [102] No details
❌ [103] Not matched
❌ [104] Not matched
✅ [105] Matched: Looking for Peyton Place: A Novel, ["Books", "Literature & Fiction", "Contemporary"], This book, published by Scribner in its first edition on July 12, 2005, is written in English and spans 368 pages in hardcover. It has an ISBN-10 of 0743246446 and an ISBN-13 of 978-0743246446. The item weighs 1.2 pounds and its dimensions are 6.75 x 1.25 x 10 inches.
❌ [106] Not matched
❌ [107] Not matched
✅ [108] Matched: All the Way to the Gallows, ["Books", "Literature & Fiction", "Short Stories & Anthologies"], This book, published by Baen in its first edition on November 1, 1996, is written in English and is available in a mass market paperback format consisting of 304 pages. It has an ISBN-10 number of 0671877534 and an ISBN-13 number of 978-0671877538. The item weighs 1.54 pounds and has dimensions of 4.19 inches in width, 1 inch in depth, and 6.75 inches in height.
❌ [109] No details
✅ [110] Matched: Can You Buy Me The Wind?, ["Books", "Children's Books", "Literature & Fiction"], Published by Lansing Press on January 1, 2015, this English-language hardcover book spans 32 pages and weighs 12.8 ounces. It is identified by the ISBN 10 number 0578152452 and the ISBN 13 number 978-0578152455.
❌ [111] No details
❌ [112] Not matched
❌ [113] Not matched
❌ [114] Not matched
❌ [115] Not matched
❌ [116] Not matched
❌ [117] Not matched
❌ [118] Not matched
❌ [119] Not matched
❌ [120] Not matched
✅ [121] Matched: Childe Harold of Dysna, ["Books", "Literature & Fiction", "History & Criticism"], The book, published by Naydus Press on July 27, 2021, is written in English and features a paperback format consisting of 80 pages. It has an ISBN 10 of 1734193603 and an ISBN 13 of 978-1734193602. Weighing 4 ounces, the book measures 4.9 by 0.3 by 7.8 inches.
❌ [122] Not matched
❌ [123] Not matched
❌ [124] Not matched
❌ [125] Not matched
❌ [126] Not matched
❌ [127] Not matched
❌ [128] Not matched
❌ [129] Not matched
❌ [130] Not matched
❌ [131] Not matched
❌ [132] Not matched
❌ [133] Not matched
❌ [134] Not matched
❌ [135] Not matched
✅ [136] Matched: Oligarchy, ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by Canongate Books in its main edition on November 7, 2019, is written in English and is available in a hardcover format comprising 224 pages. The ISBN 10 for this title is 1786897792, while the ISBN 13 is 978-1786897794. Weighing 13.5 ounces, the book has dimensions of 5.79 inches in width, 0.94 inches in depth, and 9.45 inches in height.
❌ [137] Not matched
❌ [138] Not matched
❌ [139] Not matched
❌ [140] Not matched
✅ [141] Matched: The Jordan Tracks, ["Books", "Literature & Fiction", "Contemporary"], Published by AuthorHouse on January 27, 2005, this book is written in English and consists of 224 pages. It is available in paperback format and has an ISBN of 1420813609 for the 10-digit version and 978-1420813609 for the 13-digit version. The item weighs 11.9 ounces and its dimensions are 6 x 0.57 x 9 inches.
❌ [142] Not matched
✅ [143] Matched: Forged in Blood (Freehold), ["Books", "Literature & Fiction", "Short Stories & Anthologies"], The book is published by Baen in a reissue edition dated September 25, 2018. It is written in English and is available as a mass market paperback, consisting of 528 pages. The ISBN-10 for this edition is 1481483536, while the ISBN-13 is 978-1481483537. The item weighs 8.8 ounces and has dimensions of 4.13 x 1.3 x 6.75 inches.
❌ [144] Not matched
❌ [145] Not matched
❌ [146] Not matched
❌ [147] Not matched
❌ [148] Not matched
❌ [149] Not matched
❌ [150] Not matched
❌ [151] Not matched
❌ [152] Not matched
❌ [153] Not matched
❌ [154] Not matched
❌ [155] Not matched
❌ [156] Not matched
❌ [157] Not matched
❌ [158] Not matched
❌ [159] Not matched
✅ [160] Matched: Time's Demon: BOOK II OF THE ISLEVALE CYCLE, ["Books", "Literature & Fiction", "Genre Fiction"], The book, published by Angry Robot on May 7, 2019, is available in English and has a file size of 2076 KB. It features text-to-speech capabilities and supports screen readers, with enhanced typesetting enabled. However, the X-Ray feature is not available. Additionally, Word Wise is enabled, and sticky notes can be utilized on Kindle Scribe. The print length of the book is 506 pages, and it has an associated ISBN of 0857667939.
❌ [161] Not matched
❌ [162] Not matched
❌ [163] Not matched
❌ [164] Not matched
❌ [165] Not matched
✅ [166] Matched: Dead Silence, ["Books", "Christian Books & Bibles", "Literature & Fiction"], Published by Shiloh Run Press on June 1, 2020, this book is written in English and is available in paperback format, comprising 320 pages. It has an ISBN-10 of 1643523317 and an ISBN-13 of 978-1643523316. The item weighs 10.4 ounces and its dimensions are 5.5 x 0.9 x 8.4 inches.
❌ [167] Not matched
❌ [168] Not matched
❌ [169] Not matched
✅ [170] Matched: Exits, Desires, & Slow Fires, ["Books", "Literature & Fiction", "Poetry"], The book, published by CreateSpace Independent Publishing Platform in its first edition on September 20, 2017, is written in English and consists of 83 pages. It has an ISBN 10 of 154710435X and an ISBN 13 of 978-1547104352. The item weighs 3.2 ounces and has dimensions of 5 x 0.21 x 8 inches.
❌ [171] Not matched
❌ [172] Not matched
❌ [173] Not matched
❌ [174] Not matched
❌ [175] Not matched
✅ [176] Matched: Kennebago Moments, ["Books", "Literature & Fiction", "Poetry"], This book, published by CreateSpace Independent Publishing Platform on November 24, 2010, is written in English and has a total of 52 pages. It is available in paperback format and weighs 3.2 ounces. The book's dimensions are 5.98 x 0.12 x 9.02 inches. It can be identified by its ISBN 10 number, 1453850171, and its ISBN 13 number, 978-1453850176.
❌ [177] Not matched
✅ [178] Matched: A Cherry Cola Christmas (A Cherry Cola Book Club Novel), ["Books", "Literature & Fiction", "Genre Fiction"], The book, published by Kensington on September 29, 2015, is available in English and features a paperback format comprising 304 pages. It has an ISBN-10 number of 1617733431 and an ISBN-13 number of 978-1617733437. The item weighs 5.6 ounces and its dimensions are 5.5 x 0.7 x 8.3 inches.
✅ [179] Matched: The Sludge, ["Books", "Literature & Fiction", "Genre Fiction"], The book, published by Great Old Ones Publishing in its first edition on July 5, 2016, is written in English and consists of 198 pages. It has an ISBN-10 of 0692726446 and an ISBN-13 of 978-0692726440. Weighing 10.4 ounces, the book measures 6 inches in width, 0.5 inches in thickness, and 9 inches in height.
❌ [180] Not matched
✅ [181] Matched: Liza of Lambeth, ["Books", "Literature & Fiction", "Classics"], This book, published independently on June 1, 2020, is available in English and comprises 125 pages in paperback format. It has an ISBN 13 of 979-8650407126 and weighs 6.9 ounces. The dimensions of the book are 6 x 0.32 x 9 inches.
❌ [182] Not matched
❌ [183] Not matched
❌ [184] Not matched
❌ [185] Not matched
✅ [186] Matched: Consort (A Dark(ish) Faerie Tale Book 3), ["Books", "Literature & Fiction", "Genre Fiction"], The book, published by Kaleidowords Publishing on May 11, 2018, is available in English and has a file size of 2029 KB. It supports unlimited simultaneous device usage and features Text to Speech functionality, making it accessible for various readers. Additionally, it is compatible with screen readers and offers enhanced typesetting for improved readability. While the X Ray feature is not enabled, Word Wise is available to assist with understanding the text. Readers can also take sticky notes using Kindle Scribe. The book comprises 284 pages, and its ISBN for page numbers is 1725153327.
✅ [187] Matched: The Vampyre and Other Tales of the Macabre (Oxford World's Classics), ["Books", "Literature & Fiction", "Genre Fiction"], This book, published by Oxford University Press in its first edition on October 15, 2008, is written in English and spans 320 pages. It has an ISBN-10 of 019955241X and an ISBN-13 of 978-0199552412. Suitable for readers aged 13 and up, it features a Lexile measure of 1360L. Weighing 8.1 ounces, the book has dimensions of 7.6 inches in height, 0.6 inches in thickness, and 5 inches in width.
❌ [188] Not matched
❌ [189] Not matched
❌ [190] Not matched
❌ [191] Not matched
❌ [192] Not matched
❌ [193] Not matched
✅ [194] Matched: Something That Feels Like Truth (Switchgrass Books), ["Books", "Literature & Fiction", "Short Stories & Anthologies"], This book, published by Northern Illinois University Press in its first edition on September 1, 2013, is available in English and is presented in paperback format with a total of 290 pages. It has an ISBN-10 of 9780875806938 and an ISBN-13 of 978-0875806938. Suitable for readers aged 18 years and older, the book weighs 11.7 ounces and its dimensions are 5 x 0.9 x 8 inches.

In [27]:
import sqlite3
import json

# ========== Step 3: Load reviews from SQLite ========== #
def fetch_reviews():
    try:
        conn = sqlite3.connect("../query_dataset/review_query.db")
        query = "SELECT * FROM review"
        df = pd.read_sql(query, conn)
        conn.close()
        print(f"✅ Loaded {len(df)} reviews")
        return df
    except Exception as e:
        print(f"❌ SQLite load failed: {e}")
        return pd.DataFrame()

df_review = fetch_reviews()

# ========== Step 4: Infer purchase_id → book_id mapping rule ========== #
def get_mapping_rule(book_ids, purchase_ids):
    prompt = (
        "You are given two complete ID columns from two different datasets:\n"
        f"- The first column is `purchase_id`: {json.dumps(purchase_ids, indent=2)}\n"
        f"- The second column is `book_id`: {json.dumps(book_ids, indent=2)}\n\n"
        "Each purchase_id corresponds to a book_id, but the mapping rule is not provided.\n"
        "Determine the mapping relationship between the two sets of IDs.\n"
        "Please respond with:\n"
        "1. The exact mapping rule in plain English \n"
        "2. An explanation of why you think this rule holds."
    )
    response = client.chat.completions.create(
        model=deployment_name,
        messages=[
            {"role": "system", "content": "You are a data engineer analyzing two columns of IDs for structural relationships."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.0,
        max_tokens=500
    )
    return response.choices[0].message.content.strip()

book_ids = [b["book_id"] for b in books]
purchase_ids = df_review["purchase_id"].drop_duplicates().tolist()
mapping_rule_explanation = get_mapping_rule(book_ids, purchase_ids)
print("\n🧠 GPT-inferred mapping rule:\n")
print(mapping_rule_explanation)

# ========== Step 5: Apply rule to each review ========== #
def resolve_purchase_to_book(purchase_id):
    prompt = (
        f"The previously inferred mapping rule is:\n\n{mapping_rule_explanation}\n\n"
        f"Now, based on this rule, please determine the corresponding `book_id` for the following `purchase_id`:\n"
        f"- purchase_id: {purchase_id}\n\n"
        "Respond only with the `book_id`, e.g., 'bookid_88'."
    )
    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a data assistant that maps purchase IDs to book IDs using a known rule."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=20
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"❌ GPT error on {purchase_id}: {e}")
        return None

predicted_book_ids = []
for i, row in df_review.iterrows():
    purchase_id = row["purchase_id"]
    book_id = resolve_purchase_to_book(purchase_id)
    predicted_book_ids.append(book_id)
    print(f"[{i}] purchase_id = {purchase_id} → book_id = {book_id}")

df_review["book_id"] = predicted_book_ids

✅ Loaded 1833 reviews

🧠 GPT-inferred mapping rule:

1. **Mapping Rule**: The mapping between `purchase_id` and `book_id` is based on the numerical suffix of each ID. Specifically, the `purchase_id` with the suffix `N` corresponds to the `book_id` with the same numerical suffix `N`. For example, `purchaseid_1` maps to `bookid_1`, `purchaseid_2` maps to `bookid_2`, and so on, up to `purchaseid_200` mapping to `bookid_200`.

2. **Explanation**: This rule holds because both `purchase_id` and `book_id` follow a consistent pattern where the prefix (i.e., "purchaseid_" and "bookid_") is constant, and only the numerical part varies. Since both lists contain IDs numbered from 1 to 200, it is logical to conclude that each `purchase_id` directly corresponds to a `book_id` with the same numerical identifier. The absence of any gaps or discrepancies in the numbering further supports this mapping rule.
[0] purchase_id = purchaseid_186 → book_id = bookid_186
[1] purchase_id = purchaseid_191 → book_id = bookid_191
[2] purchase_id = purchaseid_190 → book_id = bookid_190
[3] purchase_id = purchaseid_8 → book_id = bookid_8
[4] purchase_id = purchaseid_178 → book_id = bookid_178
[5] purchase_id = purchaseid_186 → book_id = bookid_186
[6] purchase_id = purchaseid_76 → book_id = bookid_76
[7] purchase_id = purchaseid_186 → book_id = bookid_186
[8] purchase_id = purchaseid_115 → book_id = bookid_115
[9] purchase_id = purchaseid_167 → book_id = bookid_167
[10] purchase_id = purchaseid_188 → book_id = bookid_188
[11] purchase_id = purchaseid_23 → book_id = bookid_23
[12] purchase_id = purchaseid_196 → book_id = bookid_196
[13] purchase_id = purchaseid_196 → book_id = bookid_196
[14] purchase_id = purchaseid_3 → book_id = bookid_3
[15] purchase_id = purchaseid_48 → book_id = bookid_48
[16] purchase_id = purchaseid_154 → book_id = bookid_154
[17] purchase_id = purchaseid_99 → book_id = bookid_99
[18] purchase_id = purchaseid_190 → book_id = bookid_190
[19] purchase_id = purchaseid_3 → book_id = bookid_3
[20] purchase_id = purchaseid_169 → book_id = bookid_169
[21] purchase_id = purchaseid_3 → book_id = bookid_3
[22] purchase_id = purchaseid_145 → book_id = bookid_145
[23] purchase_id = purchaseid_194 → book_id = bookid_194
[24] purchase_id = purchaseid_81 → book_id = bookid_81
[25] purchase_id = purchaseid_199 → book_id = bookid_199
[26] purchase_id = purchaseid_48 → book_id = bookid_48
[27] purchase_id = purchaseid_96 → book_id = bookid_96
[28] purchase_id = purchaseid_167 → book_id = bookid_167
[29] purchase_id = purchaseid_196 → book_id = bookid_196
[30] purchase_id = purchaseid_196 → book_id = bookid_196
[31] purchase_id = purchaseid_196 → book_id = bookid_196
[32] purchase_id = purchaseid_148 → book_id = bookid_148
[33] purchase_id = purchaseid_8 → book_id = bookid_8
[34] purchase_id = purchaseid_145 → book_id = bookid_145
[35] purchase_id = purchaseid_200 → book_id = bookid_200
[36] purchase_id = purchaseid_8 → book_id = bookid_8
[37] purchase_id = purchaseid_178 → book_id = bookid_178
[38] purchase_id = purchaseid_20 → book_id = bookid_20
[39] purchase_id = purchaseid_52 → book_id = bookid_52
[40] purchase_id = purchaseid_159 → book_id = bookid_159
[41] purchase_id = purchaseid_83 → book_id = bookid_83
[42] purchase_id = purchaseid_67 → book_id = bookid_67
[43] purchase_id = purchaseid_3 → book_id = bookid_3
[44] purchase_id = purchaseid_58 → book_id = bookid_58
[45] purchase_id = purchaseid_196 → book_id = bookid_196
[46] purchase_id = purchaseid_95 → book_id = bookid_95
[47] purchase_id = purchaseid_76 → book_id = bookid_76
[48] purchase_id = purchaseid_3 → book_id = bookid_3
[49] purchase_id = purchaseid_62 → book_id = bookid_62
[50] purchase_id = purchaseid_136 → book_id = bookid_136
[51] purchase_id = purchaseid_10 → book_id = bookid_10
[52] purchase_id = purchaseid_3 → book_id = bookid_3
[53] purchase_id = purchaseid_10 → book_id = bookid_10
[54] purchase_id = purchaseid_3 → book_id = bookid_3
[55] purchase_id = purchaseid_186 → book_id = bookid_186
[56] purchase_id = purchaseid_46 → book_id = bookid_46
[57] purchase_id = purchaseid_38 → book_id = bookid_38
[58] purchase_id = purchaseid_145 → book_id = bookid_145
[59] purchase_id = purchaseid_48 → book_id = bookid_48
[60] purchase_id = purchaseid_10 → book_id = bookid_10
[61] purchase_id = purchaseid_31 → book_id = bookid_31
[62] purchase_id = purchaseid_115 → book_id = bookid_115
[63] purchase_id = purchaseid_48 → book_id = bookid_48
[64] purchase_id = purchaseid_196 → book_id = bookid_196
[65] purchase_id = purchaseid_178 → book_id = bookid_178
[66] purchase_id = purchaseid_7 → book_id = bookid_7
[67] purchase_id = purchaseid_4 → book_id = bookid_4
[68] purchase_id = purchaseid_104 → book_id = bookid_104
[69] purchase_id = purchaseid_8 → book_id = bookid_8
[70] purchase_id = purchaseid_162 → book_id = bookid_162
[71] purchase_id = purchaseid_145 → book_id = bookid_145
[72] purchase_id = purchaseid_8 → book_id = bookid_8
[73] purchase_id = purchaseid_3 → book_id = bookid_3
[74] purchase_id = purchaseid_186 → book_id = bookid_186
[75] purchase_id = purchaseid_5 → book_id = bookid_5
[76] purchase_id = purchaseid_20 → book_id = bookid_20
[77] purchase_id = purchaseid_158 → book_id = bookid_158
[78] purchase_id = purchaseid_8 → book_id = bookid_8
[79] purchase_id = purchaseid_165 → book_id = bookid_165
[80] purchase_id = purchaseid_8 → book_id = bookid_8
[81] purchase_id = purchaseid_6 → book_id = bookid_6
[82] purchase_id = purchaseid_158 → book_id = bookid_158
[83] purchase_id = purchaseid_196 → book_id = bookid_196
[84] purchase_id = purchaseid_5 → book_id = bookid_5
[85] purchase_id = purchaseid_8 → book_id = bookid_8
[86] purchase_id = purchaseid_115 → book_id = bookid_115
[87] purchase_id = purchaseid_46 → book_id = bookid_46
[88] purchase_id = purchaseid_83 → book_id = bookid_83
[89] purchase_id = purchaseid_86 → book_id = bookid_86
[90] purchase_id = purchaseid_174 → book_id = bookid_174
[91] purchase_id = purchaseid_178 → book_id = bookid_178
[92] purchase_id = purchaseid_8 → book_id = bookid_8
[93] purchase_id = purchaseid_48 → book_id = bookid_48
[94] purchase_id = purchaseid_8 → book_id = bookid_8
[95] purchase_id = purchaseid_3 → book_id = bookid_3
[96] purchase_id = purchaseid_3 → book_id = bookid_3
[97] purchase_id = purchaseid_177 → book_id = bookid_177
[98] purchase_id = purchaseid_187 → book_id = bookid_187
[99] purchase_id = purchaseid_188 → book_id = bookid_188
[100] purchase_id = purchaseid_8 → book_id = bookid_8
[101] purchase_id = purchaseid_63 → book_id = bookid_63
[102] purchase_id = purchaseid_33 → book_id = bookid_33
[103] purchase_id = purchaseid_178 → book_id = bookid_178
[104] purchase_id = purchaseid_178 → book_id = bookid_178
[105] purchase_id = purchaseid_178 → book_id = bookid_178
[106] purchase_id = purchaseid_62 → book_id = bookid_62
[107] purchase_id = purchaseid_10 → book_id = bookid_10
[108] purchase_id = purchaseid_48 → book_id = bookid_48
[109] purchase_id = purchaseid_8 → book_id = bookid_8
[110] purchase_id = purchaseid_62 → book_id = bookid_62
[111] purchase_id = purchaseid_178 → book_id = bookid_178
[112] purchase_id = purchaseid_32 → book_id = bookid_32
[113] purchase_id = purchaseid_157 → book_id = bookid_157
[114] purchase_id = purchaseid_193 → book_id = bookid_193
[115] purchase_id = purchaseid_196 → book_id = bookid_196
[116] purchase_id = purchaseid_186 → book_id = bookid_186
[117] purchase_id = purchaseid_185 → book_id = bookid_185
[118] purchase_id = purchaseid_178 → book_id = bookid_178
[119] purchase_id = purchaseid_187 → book_id = bookid_187
[120] purchase_id = purchaseid_178 → book_id = bookid_178
[121] purchase_id = purchaseid_196 → book_id = bookid_196
[122] purchase_id = purchaseid_13 → book_id = bookid_13
[123] purchase_id = purchaseid_3 → book_id = bookid_3
[124] purchase_id = purchaseid_72 → book_id = bookid_72
[125] purchase_id = purchaseid_196 → book_id = bookid_196
[126] purchase_id = purchaseid_42 → book_id = bookid_42
[127] purchase_id = purchaseid_96 → book_id = bookid_96
[128] purchase_id = purchaseid_73 → book_id = bookid_73
[129] purchase_id = purchaseid_188 → book_id = bookid_188
[130] purchase_id = purchaseid_145 → book_id = bookid_145
[131] purchase_id = purchaseid_97 → book_id = bookid_97
[132] purchase_id = purchaseid_59 → book_id = bookid_59
[133] purchase_id = purchaseid_192 → book_id = bookid_192
[134] purchase_id = purchaseid_178 → book_id = bookid_178
[135] purchase_id = purchaseid_193 → book_id = bookid_193
[136] purchase_id = purchaseid_8 → book_id = bookid_8
[137] purchase_id = purchaseid_178 → book_id = bookid_178
[138] purchase_id = purchaseid_109 → book_id = bookid_109
[139] purchase_id = purchaseid_3 → book_id = bookid_3
[140] purchase_id = purchaseid_99 → book_id = bookid_99
[141] purchase_id = purchaseid_76 → book_id = bookid_76
[142] purchase_id = purchaseid_3 → book_id = bookid_3
[143] purchase_id = purchaseid_8 → book_id = bookid_8
[144] purchase_id = purchaseid_3 → book_id = bookid_3
[145] purchase_id = purchaseid_154 → book_id = bookid_154
[146] purchase_id = purchaseid_148 → book_id = bookid_148
[147] purchase_id = purchaseid_178 → book_id = bookid_178
[148] purchase_id = purchaseid_163 → book_id = bookid_163
[149] purchase_id = purchaseid_178 → book_id = bookid_178
[150] purchase_id = purchaseid_178 → book_id = bookid_178
[151] purchase_id = purchaseid_178 → book_id = bookid_178
[152] purchase_id = purchaseid_52 → book_id = bookid_52
[153] purchase_id = purchaseid_109 → book_id = bookid_109
[154] purchase_id = purchaseid_196 → book_id = bookid_196
[155] purchase_id = purchaseid_196 → book_id = bookid_196
[156] purchase_id = purchaseid_106 → book_id = bookid_106
[157] purchase_id = purchaseid_130 → book_id = bookid_130
[158] purchase_id = purchaseid_118 → book_id = bookid_118
[159] purchase_id = purchaseid_167 → book_id = bookid_167
[160] purchase_id = purchaseid_8 → book_id = bookid_8
[161] purchase_id = purchaseid_103 → book_id = bookid_103
[162] purchase_id = purchaseid_8 → book_id = bookid_8
[163] purchase_id = purchaseid_5 → book_id = bookid_5
[164] purchase_id = purchaseid_8 → book_id = bookid_8
[165] purchase_id = purchaseid_103 → book_id = bookid_103
[166] purchase_id = purchaseid_5 → book_id = bookid_5
[167] purchase_id = purchaseid_3 → book_id = bookid_3
[168] purchase_id = purchaseid_20 → book_id = bookid_20
[169] purchase_id = purchaseid_3 → book_id = bookid_3
[170] purchase_id = purchaseid_8 → book_id = bookid_8
[171] purchase_id = purchaseid_8 → book_id = bookid_8
[172] purchase_id = purchaseid_178 → book_id = bookid_178
[173] purchase_id = purchaseid_178 → book_id = bookid_178
[174] purchase_id = purchaseid_115 → book_id = bookid_115
[175] purchase_id = purchaseid_3 → book_id = bookid_3
[176] purchase_id = purchaseid_8 → book_id = bookid_8
[177] purchase_id = purchaseid_154 → book_id = bookid_154
[178] purchase_id = purchaseid_8 → book_id = bookid_8
[179] purchase_id = purchaseid_154 → book_id = bookid_154
[180] purchase_id = purchaseid_32 → book_id = bookid_32
[181] purchase_id = purchaseid_186 → book_id = bookid_186
[182] purchase_id = purchaseid_161 → book_id = bookid_161
[183] purchase_id = purchaseid_41 → book_id = bookid_41
[184] purchase_id = purchaseid_36 → book_id = bookid_36
[185] purchase_id = purchaseid_145 → book_id = bookid_145
[186] purchase_id = purchaseid_196 → book_id = bookid_196
[187] purchase_id = purchaseid_8 → book_id = bookid_8
[188] purchase_id = purchaseid_145 → book_id = bookid_145
[189] purchase_id = purchaseid_20 → book_id = bookid_20
[190] purchase_id = purchaseid_124 → book_id = bookid_124
[191] purchase_id = purchaseid_48 → book_id = bookid_48
[192] purchase_id = purchaseid_32 → book_id = bookid_32
[193] purchase_id = purchaseid_196 → book_id = bookid_196
[194] purchase_id = purchaseid_3 → book_id = bookid_3
[195] purchase_id = purchaseid_148 → book_id = bookid_148
[196] purchase_id = purchaseid_196 → book_id = bookid_196
[197] purchase_id = purchaseid_197 → book_id = bookid_197
[198] purchase_id = purchaseid_196 → book_id = bookid_196
[199] purchase_id = purchaseid_41 → book_id = bookid_41
[200] purchase_id = purchaseid_196 → book_id = bookid_196
[201] purchase_id = purchaseid_178 → book_id = bookid_178
[202] purchase_id = purchaseid_173 → book_id = bookid_173
[203] purchase_id = purchaseid_178 → book_id = bookid_178
[204] purchase_id = purchaseid_5 → book_id = bookid_5
[205] purchase_id = purchaseid_8 → book_id = bookid_8
[206] purchase_id = purchaseid_83 → book_id = bookid_83
[207] purchase_id = purchaseid_178 → book_id = bookid_178
[208] purchase_id = purchaseid_8 → book_id = bookid_8
[209] purchase_id = purchaseid_5 → book_id = bookid_5
[210] purchase_id = purchaseid_12 → book_id = bookid_12
[211] purchase_id = purchaseid_3 → book_id = bookid_3
[212] purchase_id = purchaseid_8 → book_id = bookid_8
[213] purchase_id = purchaseid_46 → book_id = bookid_46
[214] purchase_id = purchaseid_140 → book_id = bookid_140
[215] purchase_id = purchaseid_72 → book_id = bookid_72
[216] purchase_id = purchaseid_120 → book_id = bookid_120
[217] purchase_id = purchaseid_8 → book_id = bookid_8
[218] purchase_id = purchaseid_166 → book_id = bookid_166
[219] purchase_id = purchaseid_178 → book_id = bookid_178
[220] purchase_id = purchaseid_196 → book_id = bookid_196
[221] purchase_id = purchaseid_8 → book_id = bookid_8
[222] purchase_id = purchaseid_85 → book_id = bookid_85
[223] purchase_id = purchaseid_94 → book_id = bookid_94
[224] purchase_id = purchaseid_72 → book_id = bookid_72
[225] purchase_id = purchaseid_178 → book_id = bookid_178
[226] purchase_id = purchaseid_194 → book_id = bookid_194
[227] purchase_id = purchaseid_186 → book_id = bookid_186
[228] purchase_id = purchaseid_145 → book_id = bookid_145
[229] purchase_id = purchaseid_3 → book_id = bookid_3
[230] purchase_id = purchaseid_187 → book_id = bookid_187
[231] purchase_id = purchaseid_8 → book_id = bookid_8
[232] purchase_id = purchaseid_72 → book_id = bookid_72
[233] purchase_id = purchaseid_48 → book_id = bookid_48
[234] purchase_id = purchaseid_90 → book_id = bookid_90
[235] purchase_id = purchaseid_186 → book_id = bookid_186
[236] purchase_id = purchaseid_133 → book_id = bookid_133
[237] purchase_id = purchaseid_160 → book_id = bookid_160
[238] purchase_id = purchaseid_20 → book_id = bookid_20
[239] purchase_id = purchaseid_148 → book_id = bookid_148
[240] purchase_id = purchaseid_62 → book_id = bookid_62
[241] purchase_id = purchaseid_161 → book_id = bookid_161
[242] purchase_id = purchaseid_8 → book_id = bookid_8
[243] purchase_id = purchaseid_62 → book_id = bookid_62
[244] purchase_id = purchaseid_178 → book_id = bookid_178
[245] purchase_id = purchaseid_181 → book_id = bookid_181
[246] purchase_id = purchaseid_186 → book_id = bookid_186
[247] purchase_id = purchaseid_8 → book_id = bookid_8
[248] purchase_id = purchaseid_8 → book_id = bookid_8
[249] purchase_id = purchaseid_145 → book_id = bookid_145
[250] purchase_id = purchaseid_131 → book_id = bookid_131
[251] purchase_id = purchaseid_185 → book_id = bookid_185
[252] purchase_id = purchaseid_195 → book_id = bookid_195
[253] purchase_id = purchaseid_186 → book_id = bookid_186
[254] purchase_id = purchaseid_113 → book_id = bookid_113
[255] purchase_id = purchaseid_129 → book_id = bookid_129
[256] purchase_id = purchaseid_190 → book_id = bookid_190
[257] purchase_id = purchaseid_196 → book_id = bookid_196
[258] purchase_id = purchaseid_46 → book_id = bookid_46
[259] purchase_id = purchaseid_154 → book_id = bookid_154
[260] purchase_id = purchaseid_10 → book_id = bookid_10
[261] purchase_id = purchaseid_3 → book_id = bookid_3
[262] purchase_id = purchaseid_48 → book_id = bookid_48
[263] purchase_id = purchaseid_20 → book_id = bookid_20
[264] purchase_id = purchaseid_62 → book_id = bookid_62
[265] purchase_id = purchaseid_84 → book_id = bookid_84
[266] purchase_id = purchaseid_20 → book_id = bookid_20
[267] purchase_id = purchaseid_32 → book_id = bookid_32
[268] purchase_id = purchaseid_196 → book_id = bookid_196
[269] purchase_id = purchaseid_8 → book_id = bookid_8
[270] purchase_id = purchaseid_20 → book_id = bookid_20
[271] purchase_id = purchaseid_76 → book_id = bookid_76
[272] purchase_id = purchaseid_170 → book_id = bookid_170
[273] purchase_id = purchaseid_178 → book_id = bookid_178
[274] purchase_id = purchaseid_53 → book_id = bookid_53
[275] purchase_id = purchaseid_178 → book_id = bookid_178
[276] purchase_id = purchaseid_141 → book_id = bookid_141
[277] purchase_id = purchaseid_62 → book_id = bookid_62
[278] purchase_id = purchaseid_186 → book_id = bookid_186
[279] purchase_id = purchaseid_186 → book_id = bookid_186
[280] purchase_id = purchaseid_186 → book_id = bookid_186
[281] purchase_id = purchaseid_186 → book_id = bookid_186
[282] purchase_id = purchaseid_186 → book_id = bookid_186
[283] purchase_id = purchaseid_186 → book_id = bookid_186
[284] purchase_id = purchaseid_186 → book_id = bookid_186
[285] purchase_id = purchaseid_186 → book_id = bookid_186
[286] purchase_id = purchaseid_186 → book_id = bookid_186
[287] purchase_id = purchaseid_186 → book_id = bookid_186
[288] purchase_id = purchaseid_186 → book_id = bookid_186
[289] purchase_id = purchaseid_186 → book_id = bookid_186
[290] purchase_id = purchaseid_8 → book_id = bookid_8
[291] purchase_id = purchaseid_137 → book_id = bookid_137
[292] purchase_id = purchaseid_72 → book_id = bookid_72
[293] purchase_id = purchaseid_115 → book_id = bookid_115
[294] purchase_id = purchaseid_8 → book_id = bookid_8
[295] purchase_id = purchaseid_186 → book_id = bookid_186
[296] purchase_id = purchaseid_178 → book_id = bookid_178
[297] purchase_id = purchaseid_178 → book_id = bookid_178
[298] purchase_id = purchaseid_167 → book_id = bookid_167
[299] purchase_id = purchaseid_23 → book_id = bookid_23
[300] purchase_id = purchaseid_167 → book_id = bookid_167
[301] purchase_id = purchaseid_67 → book_id = bookid_67
[302] purchase_id = purchaseid_99 → book_id = bookid_99
[303] purchase_id = purchaseid_198 → book_id = bookid_198
[304] purchase_id = purchaseid_95 → book_id = bookid_95
[305] purchase_id = purchaseid_8 → book_id = bookid_8
[306] purchase_id = purchaseid_83 → book_id = bookid_83
[307] purchase_id = purchaseid_196 → book_id = bookid_196
[308] purchase_id = purchaseid_178 → book_id = bookid_178
[309] purchase_id = purchaseid_3 → book_id = bookid_3
[310] purchase_id = purchaseid_8 → book_id = bookid_8
[311] purchase_id = purchaseid_129 → book_id = bookid_129
[312] purchase_id = purchaseid_3 → book_id = bookid_3
[313] purchase_id = purchaseid_178 → book_id = bookid_178
[314] purchase_id = purchaseid_3 → book_id = bookid_3
[315] purchase_id = purchaseid_3 → book_id = bookid_3
[316] purchase_id = purchaseid_58 → book_id = bookid_58
[317] purchase_id = purchaseid_178 → book_id = bookid_178
[318] purchase_id = purchaseid_186 → book_id = bookid_186
[319] purchase_id = purchaseid_94 → book_id = bookid_94
[320] purchase_id = purchaseid_20 → book_id = bookid_20
[321] purchase_id = purchaseid_125 → book_id = bookid_125
[322] purchase_id = purchaseid_10 → book_id = bookid_10
[323] purchase_id = purchaseid_158 → book_id = bookid_158
[324] purchase_id = purchaseid_38 → book_id = bookid_38
[325] purchase_id = purchaseid_129 → book_id = bookid_129
[326] purchase_id = purchaseid_28 → book_id = bookid_28
[327] purchase_id = purchaseid_8 → book_id = bookid_8
[328] purchase_id = purchaseid_52 → book_id = bookid_52
[329] purchase_id = purchaseid_8 → book_id = bookid_8
[330] purchase_id = purchaseid_178 → book_id = bookid_178
[331] purchase_id = purchaseid_5 → book_id = bookid_5
[332] purchase_id = purchaseid_196 → book_id = bookid_196
[333] purchase_id = purchaseid_8 → book_id = bookid_8
[334] purchase_id = purchaseid_193 → book_id = bookid_193
[335] purchase_id = purchaseid_8 → book_id = bookid_8
[336] purchase_id = purchaseid_8 → book_id = bookid_8
[337] purchase_id = purchaseid_169 → book_id = bookid_169
[338] purchase_id = purchaseid_178 → book_id = bookid_178

In [ ]:
import pandas as pd


# ===== Step 3: 清洗评分列 =====
df_review["rating"] = pd.to_numeric(df_review["rating"], errors="coerce")
df_review = df_review[df_review["rating"].notnull()]

# ===== Step 4: 只保留出现在 df_qualified 中的书 =====
qualified_book_ids = set(df_qualified["book_id"])
df_filtered = df_review[df_review["book_id"].isin(qualified_book_ids)].copy()

# ===== Step 5: 按 book_id 计算平均评分 =====
df_grouped = (
    df_filtered.groupby("book_id")
    .agg(avg_rating=("rating", "mean"), num_reviews=("rating", "count"))
    .reset_index()
)

# ===== Step 6: 只保留平均评分恰好为 5.0 的书 =====
df_perfect = df_grouped[df_grouped["avg_rating"] == 5.0].copy()

# ===== Step 7: 加入书名（title）信息 =====
# Step 7: 加入 title 和 categories 信息
df_result = df_perfect.merge(
    df_qualified[["book_id", "title", "categories"]], on="book_id", how="left"
)

# Step 7.5: 进一步过滤，确保 categories 明确包含 'Literature & Fiction'
df_result = df_result[df_result["categories"].str.contains("Literature & Fiction", case=False, na=False)]

# Step 8: 输出结果
print("📚 English Literature & Fiction books with perfect average rating of 5.0 (verified categories):")
print(df_result[["title", "categories"]])

📚 English Literature & Fiction books with perfect average rating of 5.0 (verified categories):
                                                title  \
0            Knowing When To Die: Uncollected Stories
1                              Childe Harold of Dysna
2                          Forged in Blood (Freehold)
3                        Exits, Desires, & Slow Fires
4                                   Kennebago Moments
5                                          The Sludge
6                                     Liza of Lambeth
7   Something That Feels Like Truth (Switchgrass B...
8   The Prophet: With Original 1923 Illustrations ...
9                      The Melancholy Strumpet Master
10  Child Of The King A Journey of Hope Book 1: Ea...
11                                       Fire Cracker
12                                        Local Honey
13           Reunion: The Children of Lauderdale Park
14  Hollywood Confessions: Hollywood Headlines Boo...

                                           categories
0   ["Books", "Literature & Fiction", "Genre Ficti...
1   ["Books", "Literature & Fiction", "History & C...
2   ["Books", "Literature & Fiction", "Short Stori...
3         ["Books", "Literature & Fiction", "Poetry"]
4         ["Books", "Literature & Fiction", "Poetry"]
5   ["Books", "Literature & Fiction", "Genre Ficti...
6       ["Books", "Literature & Fiction", "Classics"]
7   ["Books", "Literature & Fiction", "Short Stori...
8         ["Books", "Literature & Fiction", "Poetry"]
9   ["Books", "Literature & Fiction", "Humor & Sat...
10                  ["Books", "Literature & Fiction"]
11  ["Books", "Literature & Fiction", "United Stat...
12                  ["Books", "Literature & Fiction"]
13  ["Books", "Literature & Fiction", "Genre Ficti...
14  ["Books", "Literature & Fiction", "Genre Ficti...